/**
 * Teks halaman /daftar dalam 6 bahasa. Pilihan bahasa disimpan di localStorage yang SAMA dengan
 * halaman /login ("nexbill_login_lang"), jadi bahasa yang dipilih di salah satunya ikut di yang
 * lain; kalau belum pernah memilih, dipakai bahasa landing page (nexbill_landing_lang) atau ?lang=.
 * Placeholder {nama} diganti oleh fmt()/rich() di page.tsx.
 */
export type DaftarLang = "id" | "en" | "ms" | "th" | "fil" | "vi";

export const DAFTAR_LANGS: { code: DaftarLang; label: string; flag: string }[] = [
  { code: "id", label: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "ms", label: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "th", label: "ไทย", flag: "🇹🇭" },
  { code: "fil", label: "Filipino", flag: "🇵🇭" },
  { code: "vi", label: "Tiếng Việt", flag: "🇻🇳" },
];

export const DAFTAR_LANG_STORAGE_KEY = "nexbill_login_lang";
export const LANDING_LANG_STORAGE_KEY = "nexbill_landing_lang";

export interface DaftarCopy {
  language: string;
  steps: [string, string, string, string, string, string];
  title: string;
  subtitle: string;
  busyOverlay: string;
  referral: string;
  stepLabel: string;
  verifiedGoogle: string;
  googleButton: string;
  googleButtonBusy: string;
  orManual: string;
  googleError: string;
  businessName: string;
  businessPlaceholder: string;
  address: string;
  phone: string;
  country: string;
  countryHint: string;
  branchQuestion: string;
  branchHint: string;
  tvQuestion: string;
  tvAndroid: string;
  tvSmart: string;
  tvAnalog: string;
  tvSmartPlugNeeded: string;
  units: string;
  perMonth: string;
  tvEstimate: string;
  tvMinUnits: string;
  tvAllAndroid: string;
  tvNone: string;
  shiftsQuestion: string;
  employeesQuestion: string;
  roleKasir: string;
  roleDapur: string;
  roleLainnya: string;
  staffTotal: string;
  outletName: string;
  ownerName: string;
  ownerEmail: string;
  googleNoPassword: string;
  password: string;
  confirmPassword: string;
  reviewBusiness: string;
  reviewOutlet: string;
  reviewBranches: string;
  reviewUnits: string;
  reviewUnitsValue: string;
  reviewShift: string;
  reviewStaff: string;
  reviewStaffValue: string;
  reviewOwner: string;
  reviewNote: string;
  reviewBranchesExtra: string;
  back: string;
  next: string;
  processing: string;
  submit: string;
  consent: string;
  terms: string;
  privacy: string;
  haveAccount: string;
  loginHere: string;
  catalogQuestion: string;
  catalogLink: string;
  errBusinessName: string;
  errOutletName: string;
  errOwnerName: string;
  errEmail: string;
  errPasswordMin: string;
  errPasswordMatch: string;
  errRegister: string;
  errTimeout: string;
  errNetwork: string;
  successTitle: string;
  successBody: string;
  successBranches: string;
  recTitle: string;
  recSmartPlug: string;
  recSmartPlugNote: string;
  recPlan: string;
  recPlanDetail: string;
  recStaff: string;
  recStaffValue: string;
  recStaffNote: string;
  successNote: string;
  toBilling: string;
  toDashboard: string;
}

export const DAFTAR_COPY: Record<DaftarLang, DaftarCopy> = {
  id: {
    language: "Bahasa",
    steps: ["Usaha", "Cabang", "TV & Konsol", "Operasional", "Akun Owner", "Review"],
    title: "Daftar NEXBILL",
    subtitle: "Coba gratis 30 hari — beberapa pertanyaan singkat dulu untuk menyiapkan akunmu.",
    busyOverlay: "Menyiapkan outlet & akun kamu...",
    referral: "Kode referral {code} terdeteksi — kamu dapat diskon {pct} untuk tagihan langganan pertama.",
    stepLabel: "Langkah {n}/{total} — {name}",
    verifiedGoogle: "Terverifikasi via Google: {email}",
    googleButton: "Daftar dengan Google",
    googleButtonBusy: "Membuka Google...",
    orManual: "atau isi manual",
    googleError: "Daftar dengan Google gagal. Coba lagi, atau isi manual di bawah.",
    businessName: "Nama Usaha",
    businessPlaceholder: "cth. Rental PS Jaya Bersama",
    address: "Alamat (opsional)",
    phone: "No. Telepon/WhatsApp (opsional)",
    country: "Negara",
    countryHint: "Menentukan simbol mata uang (Rp, RM, ฿, dst.) yang tampil di seluruh dashboard outlet ini — bisa diganti lagi nanti di Pengaturan.",
    branchQuestion: "Berapa jumlah cabang yang kamu miliki (termasuk yang ini)?",
    branchHint: "Kalau lebih dari 1, cabang lain otomatis dibuat sekaligus dan digabung dalam satu tagihan (billing group) — bisa diganti nama/alamatnya nanti di menu Pengaturan.",
    tvQuestion: "Berapa banyak unit TV di outlet ini, berdasarkan jenisnya?",
    tvAndroid: "TV Android",
    tvSmart: "Smart TV",
    tvAnalog: "TV Analog",
    tvSmartPlugNeeded: "TV analog/smart TV butuh Smart Plug agar bisa dikontrol otomatis dari sistem — {n}",
    units: "{n} unit",
    perMonth: "/bln",
    tvEstimate: "Estimasi setelah trial 30 hari: {starter} ({units} × {price}{min}) atau {pro} (unit tak terbatas + akuntansi, aset, PPOB, anti-fraud, AI, multi-cabang). Tahunan: bayar {months} bulan, aktif 12 bulan.",
    tvMinUnits: ", minimal {n} unit",
    tvAllAndroid: "Semua unit TV Android — tidak perlu smart plug untuk memulai.",
    tvNone: "Belum ada unit diisi — bisa ditambah kapan saja nanti di menu Kelola Unit.",
    shiftsQuestion: "Berapa shift kerja saat ini?",
    employeesQuestion: "Berapa karyawan per peran (di luar owner)?",
    roleKasir: "Kasir",
    roleDapur: "Dapur",
    roleLainnya: "Lainnya",
    staffTotal: "Total {n} akun staf disarankan (akan dibuatkan manual di menu Staf setelah masuk — biar kamu yang atur email/password masing-masing).",
    outletName: "Nama Outlet/Merchant (tampil di struk & halaman booking publik)",
    ownerName: "Nama Pemilik (Owner)",
    ownerEmail: "Email Owner (untuk login)",
    googleNoPassword: "Terverifikasi via Google — tidak perlu password, login berikutnya cukup pakai tombol \"Masuk dengan Google\".",
    password: "Password",
    confirmPassword: "Konfirmasi Password",
    reviewBusiness: "Usaha:",
    reviewOutlet: "Outlet pertama:",
    reviewBranches: "Jumlah cabang:",
    reviewUnits: "Unit TV:",
    reviewUnitsValue: "{a} Android, {s} Smart TV, {g} Analog (total {t})",
    reviewShift: "Shift:",
    reviewStaff: "Karyawan:",
    reviewStaffValue: "{k} kasir, {d} dapur, {l} lainnya",
    reviewOwner: "Owner:",
    reviewNote: "Dengan mendaftar, satu outlet {branches}dan satu akun Owner akan langsung dibuat, lengkap dengan masa percobaan 30 hari.",
    reviewBranchesExtra: "(+{n} cabang) ",
    back: "Kembali",
    next: "Lanjut",
    processing: "Memproses...",
    submit: "Daftar Sekarang",
    consent: "Dengan mendaftar, Anda menyetujui {terms} dan {privacy} NEXBILL.",
    terms: "Syarat & Ketentuan",
    privacy: "Kebijakan Privasi",
    haveAccount: "Sudah punya akun?",
    loginHere: "Masuk di sini",
    catalogQuestion: "Ingin tahu semua fiturnya dulu?",
    catalogLink: "Lihat Katalog Fitur NEXBILL",
    errBusinessName: "Nama usaha wajib diisi.",
    errOutletName: "Nama outlet/merchant wajib diisi.",
    errOwnerName: "Nama pemilik (owner) wajib diisi.",
    errEmail: "Email tidak valid.",
    errPasswordMin: "Password minimal 8 karakter.",
    errPasswordMatch: "Konfirmasi password tidak sama.",
    errRegister: "Pendaftaran gagal.",
    errTimeout: "Pendaftaran butuh waktu lebih lama dari biasanya (kemungkinan server sedang sibuk). Coba lagi sebentar lagi.",
    errNetwork: "Tidak bisa terhubung ke server. Cek koneksi internet kamu dan coba lagi.",
    successTitle: "Pendaftaran Berhasil 🎉",
    successBody: "Outlet {outlet} sudah dibuat{branches}. Masa percobaan 30 hari sudah aktif.",
    successBranches: " beserta {n} cabang lainnya",
    recTitle: "Rekomendasi Berdasarkan Jawabanmu",
    recSmartPlug: "Smart Plug dibutuhkan:",
    recSmartPlugNote: "(untuk TV analog/smart TV)",
    recPlan: "Paket yang disarankan:",
    recPlanDetail: "Starter {starter}/bln ({units} unit) · Pro {pro}/bln (unit tak terbatas + semua fitur). Bebas pilih setelah trial.",
    recStaff: "Estimasi akun staf yang perlu dibuat:",
    recStaffValue: "{n} akun",
    recStaffNote: "(kasir/dapur/lainnya), untuk {shifts} shift",
    successNote: "Kamu sudah otomatis masuk (login). Lanjutkan ke halaman Langganan untuk memilih paket (Starter/Pro) dan membeli smart plug, atau langsung ke Dashboard.",
    toBilling: "Ke Halaman Langganan",
    toDashboard: "Ke Dashboard",
  },
  en: {
    language: "Language",
    steps: ["Business", "Branches", "TVs & Consoles", "Operations", "Owner Account", "Review"],
    title: "Sign up for NEXBILL",
    subtitle: "Free for 30 days — a few quick questions first to set up your account.",
    busyOverlay: "Setting up your outlet & account...",
    referral: "Referral code {code} detected — you get a {pct} discount on your first subscription bill.",
    stepLabel: "Step {n}/{total} — {name}",
    verifiedGoogle: "Verified with Google: {email}",
    googleButton: "Sign up with Google",
    googleButtonBusy: "Opening Google...",
    orManual: "or fill in manually",
    googleError: "Google sign-up failed. Try again, or fill in the form below.",
    businessName: "Business Name",
    businessPlaceholder: "e.g. Jaya Bersama PS Rental",
    address: "Address (optional)",
    phone: "Phone/WhatsApp (optional)",
    country: "Country",
    countryHint: "Sets the currency symbol (Rp, RM, ฿, etc.) shown across this outlet's dashboard — you can change it later in Settings.",
    branchQuestion: "How many branches do you have (including this one)?",
    branchHint: "If more than 1, the other branches are created at once and grouped on one bill (billing group) — you can rename them or change addresses later in Settings.",
    tvQuestion: "How many TV units does this outlet have, by type?",
    tvAndroid: "Android TV",
    tvSmart: "Smart TV",
    tvAnalog: "Analog TV",
    tvSmartPlugNeeded: "Analog/smart TVs need a Smart Plug to be controlled automatically by the system — {n}",
    units: "{n} units",
    perMonth: "/mo",
    tvEstimate: "Estimate after the 30-day trial: {starter} ({units} × {price}{min}) or {pro} (unlimited units + accounting, assets, bill payments, anti-fraud, AI, multi-branch). Yearly: pay {months} months, active for 12 months.",
    tvMinUnits: ", minimum {n} units",
    tvAllAndroid: "All units are Android TVs — no smart plug needed to get started.",
    tvNone: "No units entered yet — you can add them any time later under Manage Units.",
    shiftsQuestion: "How many work shifts do you run now?",
    employeesQuestion: "How many employees per role (excluding the owner)?",
    roleKasir: "Cashier",
    roleDapur: "Kitchen",
    roleLainnya: "Other",
    staffTotal: "{n} staff accounts suggested in total (create them yourself in the Staff menu after logging in, so you control each email/password).",
    outletName: "Outlet/Merchant Name (shown on receipts & the public booking page)",
    ownerName: "Owner Name",
    ownerEmail: "Owner Email (for login)",
    googleNoPassword: "Verified with Google — no password needed, next time just use the \"Sign in with Google\" button.",
    password: "Password",
    confirmPassword: "Confirm Password",
    reviewBusiness: "Business:",
    reviewOutlet: "First outlet:",
    reviewBranches: "Branches:",
    reviewUnits: "TV units:",
    reviewUnitsValue: "{a} Android, {s} Smart TV, {g} Analog (total {t})",
    reviewShift: "Shifts:",
    reviewStaff: "Employees:",
    reviewStaffValue: "{k} cashier, {d} kitchen, {l} other",
    reviewOwner: "Owner:",
    reviewNote: "By signing up, one outlet {branches}and one Owner account are created right away, with a 30-day free trial.",
    reviewBranchesExtra: "(+{n} branches) ",
    back: "Back",
    next: "Next",
    processing: "Processing...",
    submit: "Sign Up Now",
    consent: "By signing up, you agree to NEXBILL's {terms} and {privacy}.",
    terms: "Terms & Conditions",
    privacy: "Privacy Policy",
    haveAccount: "Already have an account?",
    loginHere: "Sign in here",
    catalogQuestion: "Want to see every feature first?",
    catalogLink: "View the NEXBILL Feature Catalog",
    errBusinessName: "Business name is required.",
    errOutletName: "Outlet/merchant name is required.",
    errOwnerName: "Owner name is required.",
    errEmail: "Invalid email.",
    errPasswordMin: "Password must be at least 8 characters.",
    errPasswordMatch: "Passwords don't match.",
    errRegister: "Sign-up failed.",
    errTimeout: "Sign-up is taking longer than usual (the server may be busy). Please try again shortly.",
    errNetwork: "Can't reach the server. Check your internet connection and try again.",
    successTitle: "Sign-up Successful 🎉",
    successBody: "Outlet {outlet} has been created{branches}. Your 30-day trial is active.",
    successBranches: " along with {n} other branches",
    recTitle: "Recommendations Based on Your Answers",
    recSmartPlug: "Smart Plugs needed:",
    recSmartPlugNote: "(for analog/smart TVs)",
    recPlan: "Suggested plan:",
    recPlanDetail: "Starter {starter}/mo ({units} units) · Pro {pro}/mo (unlimited units + every feature). Choose freely after the trial.",
    recStaff: "Estimated staff accounts to create:",
    recStaffValue: "{n} accounts",
    recStaffNote: "(cashier/kitchen/other), for {shifts} shifts",
    successNote: "You're already signed in. Continue to the Subscription page to pick a plan (Starter/Pro) and buy smart plugs, or go straight to the Dashboard.",
    toBilling: "Go to Subscription",
    toDashboard: "Go to Dashboard",
  },
  ms: {
    language: "Bahasa",
    steps: ["Perniagaan", "Cawangan", "TV & Konsol", "Operasi", "Akaun Pemilik", "Semakan"],
    title: "Daftar NEXBILL",
    subtitle: "Percuma 30 hari — beberapa soalan ringkas dahulu untuk menyediakan akaun anda.",
    busyOverlay: "Menyediakan outlet & akaun anda...",
    referral: "Kod rujukan {code} dikesan — anda mendapat diskaun {pct} untuk bil langganan pertama.",
    stepLabel: "Langkah {n}/{total} — {name}",
    verifiedGoogle: "Disahkan melalui Google: {email}",
    googleButton: "Daftar dengan Google",
    googleButtonBusy: "Membuka Google...",
    orManual: "atau isi secara manual",
    googleError: "Pendaftaran dengan Google gagal. Cuba lagi, atau isi secara manual di bawah.",
    businessName: "Nama Perniagaan",
    businessPlaceholder: "cth. Sewa PS Jaya Bersama",
    address: "Alamat (pilihan)",
    phone: "No. Telefon/WhatsApp (pilihan)",
    country: "Negara",
    countryHint: "Menentukan simbol mata wang (Rp, RM, ฿, dll.) di seluruh papan pemuka outlet ini — boleh ditukar kemudian di Tetapan.",
    branchQuestion: "Berapa banyak cawangan yang anda miliki (termasuk yang ini)?",
    branchHint: "Jika lebih daripada 1, cawangan lain dibuat serentak dan digabungkan dalam satu bil (kumpulan bil) — nama/alamat boleh ditukar kemudian di Tetapan.",
    tvQuestion: "Berapa banyak unit TV di outlet ini, mengikut jenis?",
    tvAndroid: "TV Android",
    tvSmart: "Smart TV",
    tvAnalog: "TV Analog",
    tvSmartPlugNeeded: "TV analog/smart TV memerlukan Smart Plug supaya boleh dikawal secara automatik oleh sistem — {n}",
    units: "{n} unit",
    perMonth: "/bln",
    tvEstimate: "Anggaran selepas percubaan 30 hari: {starter} ({units} × {price}{min}) atau {pro} (unit tanpa had + perakaunan, aset, PPOB, anti-penipuan, AI, berbilang cawangan). Tahunan: bayar {months} bulan, aktif 12 bulan.",
    tvMinUnits: ", minimum {n} unit",
    tvAllAndroid: "Semua unit TV Android — tidak perlu smart plug untuk bermula.",
    tvNone: "Belum ada unit diisi — boleh ditambah bila-bila masa di menu Urus Unit.",
    shiftsQuestion: "Berapa syif kerja sekarang?",
    employeesQuestion: "Berapa pekerja mengikut peranan (selain pemilik)?",
    roleKasir: "Juruwang",
    roleDapur: "Dapur",
    roleLainnya: "Lain-lain",
    staffTotal: "Sejumlah {n} akaun kakitangan dicadangkan (dibuat sendiri di menu Kakitangan selepas log masuk — supaya anda yang tetapkan e-mel/kata laluan masing-masing).",
    outletName: "Nama Outlet/Peniaga (dipaparkan pada resit & halaman tempahan awam)",
    ownerName: "Nama Pemilik",
    ownerEmail: "E-mel Pemilik (untuk log masuk)",
    googleNoPassword: "Disahkan melalui Google — tiada kata laluan diperlukan, seterusnya gunakan butang \"Log masuk dengan Google\".",
    password: "Kata laluan",
    confirmPassword: "Sahkan Kata Laluan",
    reviewBusiness: "Perniagaan:",
    reviewOutlet: "Outlet pertama:",
    reviewBranches: "Bilangan cawangan:",
    reviewUnits: "Unit TV:",
    reviewUnitsValue: "{a} Android, {s} Smart TV, {g} Analog (jumlah {t})",
    reviewShift: "Syif:",
    reviewStaff: "Pekerja:",
    reviewStaffValue: "{k} juruwang, {d} dapur, {l} lain-lain",
    reviewOwner: "Pemilik:",
    reviewNote: "Dengan mendaftar, satu outlet {branches}dan satu akaun Pemilik akan terus dibuat, lengkap dengan percubaan percuma 30 hari.",
    reviewBranchesExtra: "(+{n} cawangan) ",
    back: "Kembali",
    next: "Seterusnya",
    processing: "Memproses...",
    submit: "Daftar Sekarang",
    consent: "Dengan mendaftar, anda bersetuju dengan {terms} dan {privacy} NEXBILL.",
    terms: "Terma & Syarat",
    privacy: "Dasar Privasi",
    haveAccount: "Sudah ada akaun?",
    loginHere: "Log masuk di sini",
    catalogQuestion: "Mahu lihat semua ciri dahulu?",
    catalogLink: "Lihat Katalog Ciri NEXBILL",
    errBusinessName: "Nama perniagaan wajib diisi.",
    errOutletName: "Nama outlet/peniaga wajib diisi.",
    errOwnerName: "Nama pemilik wajib diisi.",
    errEmail: "E-mel tidak sah.",
    errPasswordMin: "Kata laluan minimum 8 aksara.",
    errPasswordMatch: "Pengesahan kata laluan tidak sepadan.",
    errRegister: "Pendaftaran gagal.",
    errTimeout: "Pendaftaran mengambil masa lebih lama daripada biasa (pelayan mungkin sibuk). Cuba lagi sebentar lagi.",
    errNetwork: "Tidak dapat menghubungi pelayan. Semak sambungan internet anda dan cuba lagi.",
    successTitle: "Pendaftaran Berjaya 🎉",
    successBody: "Outlet {outlet} telah dibuat{branches}. Percubaan 30 hari anda sudah aktif.",
    successBranches: " bersama {n} cawangan lain",
    recTitle: "Cadangan Berdasarkan Jawapan Anda",
    recSmartPlug: "Smart Plug diperlukan:",
    recSmartPlugNote: "(untuk TV analog/smart TV)",
    recPlan: "Pakej dicadangkan:",
    recPlanDetail: "Starter {starter}/bln ({units} unit) · Pro {pro}/bln (unit tanpa had + semua ciri). Bebas pilih selepas percubaan.",
    recStaff: "Anggaran akaun kakitangan yang perlu dibuat:",
    recStaffValue: "{n} akaun",
    recStaffNote: "(juruwang/dapur/lain-lain), untuk {shifts} syif",
    successNote: "Anda sudah log masuk secara automatik. Teruskan ke halaman Langganan untuk memilih pakej (Starter/Pro) dan membeli smart plug, atau terus ke Papan Pemuka.",
    toBilling: "Ke Halaman Langganan",
    toDashboard: "Ke Papan Pemuka",
  },
  th: {
    language: "ภาษา",
    steps: ["ธุรกิจ", "สาขา", "ทีวีและคอนโซล", "การดำเนินงาน", "บัญชีเจ้าของ", "ตรวจสอบ"],
    title: "สมัคร NEXBILL",
    subtitle: "ใช้ฟรี 30 วัน — ตอบคำถามสั้นๆ ก่อนเพื่อตั้งค่าบัญชีของคุณ",
    busyOverlay: "กำลังเตรียมร้านและบัญชีของคุณ...",
    referral: "พบรหัสแนะนำ {code} — คุณได้รับส่วนลด {pct} สำหรับบิลค่าสมาชิกครั้งแรก",
    stepLabel: "ขั้นตอน {n}/{total} — {name}",
    verifiedGoogle: "ยืนยันผ่าน Google แล้ว: {email}",
    googleButton: "สมัครด้วย Google",
    googleButtonBusy: "กำลังเปิด Google...",
    orManual: "หรือกรอกเอง",
    googleError: "สมัครด้วย Google ไม่สำเร็จ ลองอีกครั้ง หรือกรอกข้อมูลด้านล่างเอง",
    businessName: "ชื่อธุรกิจ",
    businessPlaceholder: "เช่น ร้านเช่า PS จายาเบอร์ซามา",
    address: "ที่อยู่ (ไม่บังคับ)",
    phone: "เบอร์โทร/WhatsApp (ไม่บังคับ)",
    country: "ประเทศ",
    countryHint: "กำหนดสัญลักษณ์สกุลเงิน (Rp, RM, ฿ ฯลฯ) ที่แสดงทั่วแดชบอร์ดของร้านนี้ — เปลี่ยนได้ภายหลังในการตั้งค่า",
    branchQuestion: "คุณมีกี่สาขา (รวมสาขานี้)?",
    branchHint: "ถ้ามากกว่า 1 สาขา ระบบจะสร้างสาขาอื่นพร้อมกันและรวมเป็นบิลเดียว (กลุ่มบิล) — เปลี่ยนชื่อ/ที่อยู่ได้ภายหลังในการตั้งค่า",
    tvQuestion: "ร้านนี้มีทีวีกี่เครื่อง แยกตามประเภท?",
    tvAndroid: "Android TV",
    tvSmart: "สมาร์ททีวี",
    tvAnalog: "ทีวีอนาล็อก",
    tvSmartPlugNeeded: "ทีวีอนาล็อก/สมาร์ททีวีต้องใช้ Smart Plug เพื่อให้ระบบควบคุมอัตโนมัติ — {n}",
    units: "{n} เครื่อง",
    perMonth: "/เดือน",
    tvEstimate: "ประมาณการหลังทดลอง 30 วัน: {starter} ({units} × {price}{min}) หรือ {pro} (ไม่จำกัดเครื่อง + บัญชี สินทรัพย์ ชำระบิล ป้องกันทุจริต AI หลายสาขา) รายปี: จ่าย {months} เดือน ใช้ได้ 12 เดือน",
    tvMinUnits: ", ขั้นต่ำ {n} เครื่อง",
    tvAllAndroid: "ทุกเครื่องเป็น Android TV — ไม่ต้องใช้ smart plug เพื่อเริ่มต้น",
    tvNone: "ยังไม่ได้กรอกจำนวนเครื่อง — เพิ่มได้ทุกเมื่อในเมนูจัดการยูนิต",
    shiftsQuestion: "ตอนนี้มีกี่กะ?",
    employeesQuestion: "พนักงานแต่ละตำแหน่งมีกี่คน (ไม่รวมเจ้าของ)?",
    roleKasir: "แคชเชียร์",
    roleDapur: "ครัว",
    roleLainnya: "อื่นๆ",
    staffTotal: "แนะนำบัญชีพนักงานทั้งหมด {n} บัญชี (สร้างเองในเมนูพนักงานหลังเข้าสู่ระบบ เพื่อให้คุณกำหนดอีเมล/รหัสผ่านของแต่ละคน)",
    outletName: "ชื่อร้าน (แสดงบนใบเสร็จและหน้าจองสาธารณะ)",
    ownerName: "ชื่อเจ้าของ",
    ownerEmail: "อีเมลเจ้าของ (สำหรับเข้าสู่ระบบ)",
    googleNoPassword: "ยืนยันผ่าน Google แล้ว — ไม่ต้องใช้รหัสผ่าน ครั้งต่อไปใช้ปุ่ม \"เข้าสู่ระบบด้วย Google\"",
    password: "รหัสผ่าน",
    confirmPassword: "ยืนยันรหัสผ่าน",
    reviewBusiness: "ธุรกิจ:",
    reviewOutlet: "ร้านแรก:",
    reviewBranches: "จำนวนสาขา:",
    reviewUnits: "ทีวี:",
    reviewUnitsValue: "Android {a}, สมาร์ททีวี {s}, อนาล็อก {g} (รวม {t})",
    reviewShift: "กะ:",
    reviewStaff: "พนักงาน:",
    reviewStaffValue: "แคชเชียร์ {k}, ครัว {d}, อื่นๆ {l}",
    reviewOwner: "เจ้าของ:",
    reviewNote: "เมื่อสมัคร ระบบจะสร้างร้าน 1 แห่ง {branches}และบัญชีเจ้าของ 1 บัญชีทันที พร้อมทดลองใช้ฟรี 30 วัน",
    reviewBranchesExtra: "(+{n} สาขา) ",
    back: "ย้อนกลับ",
    next: "ถัดไป",
    processing: "กำลังดำเนินการ...",
    submit: "สมัครเลย",
    consent: "เมื่อสมัคร คุณยอมรับ{terms}และ{privacy}ของ NEXBILL",
    terms: "ข้อกำหนดและเงื่อนไข",
    privacy: "นโยบายความเป็นส่วนตัว",
    haveAccount: "มีบัญชีแล้ว?",
    loginHere: "เข้าสู่ระบบที่นี่",
    catalogQuestion: "อยากดูฟีเจอร์ทั้งหมดก่อน?",
    catalogLink: "ดูแคตตาล็อกฟีเจอร์ NEXBILL",
    errBusinessName: "ต้องกรอกชื่อธุรกิจ",
    errOutletName: "ต้องกรอกชื่อร้าน",
    errOwnerName: "ต้องกรอกชื่อเจ้าของ",
    errEmail: "อีเมลไม่ถูกต้อง",
    errPasswordMin: "รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร",
    errPasswordMatch: "ยืนยันรหัสผ่านไม่ตรงกัน",
    errRegister: "สมัครไม่สำเร็จ",
    errTimeout: "การสมัครใช้เวลานานกว่าปกติ (เซิร์ฟเวอร์อาจไม่ว่าง) โปรดลองอีกครั้งในอีกสักครู่",
    errNetwork: "เชื่อมต่อเซิร์ฟเวอร์ไม่ได้ ตรวจสอบอินเทอร์เน็ตแล้วลองอีกครั้ง",
    successTitle: "สมัครสำเร็จ 🎉",
    successBody: "สร้างร้าน {outlet} แล้ว{branches} ทดลองใช้ 30 วันเริ่มแล้ว",
    successBranches: " พร้อมสาขาอื่นอีก {n} แห่ง",
    recTitle: "คำแนะนำจากคำตอบของคุณ",
    recSmartPlug: "Smart Plug ที่ต้องใช้:",
    recSmartPlugNote: "(สำหรับทีวีอนาล็อก/สมาร์ททีวี)",
    recPlan: "แพ็กเกจที่แนะนำ:",
    recPlanDetail: "Starter {starter}/เดือน ({units} เครื่อง) · Pro {pro}/เดือน (ไม่จำกัดเครื่อง + ทุกฟีเจอร์) เลือกได้อิสระหลังทดลองใช้",
    recStaff: "จำนวนบัญชีพนักงานที่ควรสร้าง:",
    recStaffValue: "{n} บัญชี",
    recStaffNote: "(แคชเชียร์/ครัว/อื่นๆ) สำหรับ {shifts} กะ",
    successNote: "คุณเข้าสู่ระบบแล้ว ไปที่หน้าการสมัครสมาชิกเพื่อเลือกแพ็กเกจ (Starter/Pro) และซื้อ smart plug หรือไปที่แดชบอร์ดเลย",
    toBilling: "ไปหน้าการสมัครสมาชิก",
    toDashboard: "ไปที่แดชบอร์ด",
  },
  fil: {
    language: "Wika",
    steps: ["Negosyo", "Branch", "TV at Console", "Operasyon", "Account ng Owner", "Review"],
    title: "Mag-sign up sa NEXBILL",
    subtitle: "Libre sa loob ng 30 araw — ilang maikling tanong muna para maihanda ang iyong account.",
    busyOverlay: "Inihahanda ang iyong outlet at account...",
    referral: "Natukoy ang referral code {code} — may {pct} diskwento ka sa unang bill ng subscription.",
    stepLabel: "Hakbang {n}/{total} — {name}",
    verifiedGoogle: "Na-verify sa Google: {email}",
    googleButton: "Mag-sign up gamit ang Google",
    googleButtonBusy: "Binubuksan ang Google...",
    orManual: "o punan nang manu-mano",
    googleError: "Hindi natuloy ang sign-up gamit ang Google. Subukan ulit, o punan ang form sa ibaba.",
    businessName: "Pangalan ng Negosyo",
    businessPlaceholder: "hal. Jaya Bersama PS Rental",
    address: "Address (opsyonal)",
    phone: "Telepono/WhatsApp (opsyonal)",
    country: "Bansa",
    countryHint: "Itinatakda ang simbolo ng pera (Rp, RM, ฿, atbp.) sa buong dashboard ng outlet na ito — mababago mamaya sa Settings.",
    branchQuestion: "Ilan ang branch mo (kasama ang isang ito)?",
    branchHint: "Kung higit sa 1, sabay na gagawin ang ibang branch at pagsasamahin sa iisang bill (billing group) — mapapalitan ang pangalan/address mamaya sa Settings.",
    tvQuestion: "Ilang TV ang nasa outlet na ito, ayon sa uri?",
    tvAndroid: "Android TV",
    tvSmart: "Smart TV",
    tvAnalog: "Analog TV",
    tvSmartPlugNeeded: "Kailangan ng Smart Plug ang analog/smart TV para awtomatikong makontrol ng system — {n}",
    units: "{n} unit",
    perMonth: "/buwan",
    tvEstimate: "Tantiya pagkatapos ng 30-araw na trial: {starter} ({units} × {price}{min}) o {pro} (walang limitasyong unit + accounting, asset, bills payment, anti-fraud, AI, multi-branch). Taunan: magbayad ng {months} buwan, aktibo nang 12 buwan.",
    tvMinUnits: ", minimum {n} unit",
    tvAllAndroid: "Lahat ng unit ay Android TV — hindi kailangan ng smart plug para magsimula.",
    tvNone: "Wala pang unit — puwedeng idagdag kahit kailan sa Pamahalaan ang Unit.",
    shiftsQuestion: "Ilang work shift ang mayroon ngayon?",
    employeesQuestion: "Ilang empleyado bawat tungkulin (hindi kasama ang owner)?",
    roleKasir: "Cashier",
    roleDapur: "Kusina",
    roleLainnya: "Iba pa",
    staffTotal: "Kabuuang {n} staff account ang iminumungkahi (ikaw ang gagawa sa Staff menu pagka-login — para ikaw ang magtakda ng email/password ng bawat isa).",
    outletName: "Pangalan ng Outlet/Merchant (makikita sa resibo at public booking page)",
    ownerName: "Pangalan ng Owner",
    ownerEmail: "Email ng Owner (para sa login)",
    googleNoPassword: "Na-verify sa Google — hindi kailangan ng password, sa susunod gamitin lang ang \"Mag-sign in gamit ang Google\".",
    password: "Password",
    confirmPassword: "Kumpirmahin ang Password",
    reviewBusiness: "Negosyo:",
    reviewOutlet: "Unang outlet:",
    reviewBranches: "Bilang ng branch:",
    reviewUnits: "Mga TV:",
    reviewUnitsValue: "{a} Android, {s} Smart TV, {g} Analog (kabuuan {t})",
    reviewShift: "Shift:",
    reviewStaff: "Empleyado:",
    reviewStaffValue: "{k} cashier, {d} kusina, {l} iba pa",
    reviewOwner: "Owner:",
    reviewNote: "Sa pag-sign up, agad gagawin ang isang outlet {branches}at isang Owner account, kasama ang 30-araw na libreng trial.",
    reviewBranchesExtra: "(+{n} branch) ",
    back: "Bumalik",
    next: "Susunod",
    processing: "Pinoproseso...",
    submit: "Mag-sign Up Na",
    consent: "Sa pag-sign up, sumasang-ayon ka sa {terms} at {privacy} ng NEXBILL.",
    terms: "Mga Tuntunin at Kundisyon",
    privacy: "Patakaran sa Privacy",
    haveAccount: "May account na?",
    loginHere: "Mag-sign in dito",
    catalogQuestion: "Gusto mo munang makita ang lahat ng feature?",
    catalogLink: "Tingnan ang Feature Catalog ng NEXBILL",
    errBusinessName: "Kailangan ang pangalan ng negosyo.",
    errOutletName: "Kailangan ang pangalan ng outlet/merchant.",
    errOwnerName: "Kailangan ang pangalan ng owner.",
    errEmail: "Hindi wasto ang email.",
    errPasswordMin: "Dapat hindi bababa sa 8 character ang password.",
    errPasswordMatch: "Hindi magkatugma ang password.",
    errRegister: "Hindi natuloy ang sign-up.",
    errTimeout: "Mas matagal kaysa karaniwan ang sign-up (maaaring abala ang server). Subukan ulit maya-maya.",
    errNetwork: "Hindi makakonekta sa server. Suriin ang internet at subukan ulit.",
    successTitle: "Matagumpay ang Sign-up 🎉",
    successBody: "Nagawa na ang outlet na {outlet}{branches}. Aktibo na ang 30-araw na trial.",
    successBranches: " kasama ang {n} pang branch",
    recTitle: "Mga Rekomendasyon Batay sa Iyong Sagot",
    recSmartPlug: "Kailangang Smart Plug:",
    recSmartPlugNote: "(para sa analog/smart TV)",
    recPlan: "Iminumungkahing plan:",
    recPlanDetail: "Starter {starter}/buwan ({units} unit) · Pro {pro}/buwan (walang limitasyong unit + lahat ng feature). Malayang pumili pagkatapos ng trial.",
    recStaff: "Tantiyang staff account na dapat gawin:",
    recStaffValue: "{n} account",
    recStaffNote: "(cashier/kusina/iba pa), para sa {shifts} shift",
    successNote: "Naka-sign in ka na. Pumunta sa Subscription page para pumili ng plan (Starter/Pro) at bumili ng smart plug, o dumiretso sa Dashboard.",
    toBilling: "Pumunta sa Subscription",
    toDashboard: "Pumunta sa Dashboard",
  },
  vi: {
    language: "Ngôn ngữ",
    steps: ["Cơ sở", "Chi nhánh", "TV & Máy", "Vận hành", "Tài khoản chủ", "Xem lại"],
    title: "Đăng ký NEXBILL",
    subtitle: "Miễn phí 30 ngày — trả lời vài câu hỏi ngắn để thiết lập tài khoản.",
    busyOverlay: "Đang chuẩn bị cửa hàng & tài khoản của bạn...",
    referral: "Đã nhận mã giới thiệu {code} — bạn được giảm {pct} cho hóa đơn gói đầu tiên.",
    stepLabel: "Bước {n}/{total} — {name}",
    verifiedGoogle: "Đã xác minh qua Google: {email}",
    googleButton: "Đăng ký bằng Google",
    googleButtonBusy: "Đang mở Google...",
    orManual: "hoặc điền thủ công",
    googleError: "Đăng ký bằng Google thất bại. Thử lại, hoặc điền thủ công bên dưới.",
    businessName: "Tên cơ sở kinh doanh",
    businessPlaceholder: "vd. Cho thuê PS Jaya Bersama",
    address: "Địa chỉ (tùy chọn)",
    phone: "Điện thoại/WhatsApp (tùy chọn)",
    country: "Quốc gia",
    countryHint: "Quyết định ký hiệu tiền tệ (Rp, RM, ฿, v.v.) hiển thị trên toàn bộ dashboard của cửa hàng — có thể đổi sau trong Cài đặt.",
    branchQuestion: "Bạn có bao nhiêu chi nhánh (kể cả chi nhánh này)?",
    branchHint: "Nếu nhiều hơn 1, các chi nhánh khác được tạo cùng lúc và gộp chung một hóa đơn (nhóm thanh toán) — có thể đổi tên/địa chỉ sau trong Cài đặt.",
    tvQuestion: "Cửa hàng có bao nhiêu TV, theo từng loại?",
    tvAndroid: "Android TV",
    tvSmart: "Smart TV",
    tvAnalog: "TV thường",
    tvSmartPlugNeeded: "TV thường/Smart TV cần Smart Plug để hệ thống điều khiển tự động — {n}",
    units: "{n} máy",
    perMonth: "/tháng",
    tvEstimate: "Ước tính sau 30 ngày dùng thử: {starter} ({units} × {price}{min}) hoặc {pro} (không giới hạn máy + kế toán, tài sản, thanh toán hóa đơn, chống gian lận, AI, nhiều chi nhánh). Theo năm: trả {months} tháng, dùng 12 tháng.",
    tvMinUnits: ", tối thiểu {n} máy",
    tvAllAndroid: "Tất cả đều là Android TV — không cần smart plug để bắt đầu.",
    tvNone: "Chưa nhập số máy — có thể thêm bất cứ lúc nào trong menu Quản lý máy.",
    shiftsQuestion: "Hiện có bao nhiêu ca làm việc?",
    employeesQuestion: "Mỗi vai trò có bao nhiêu nhân viên (không tính chủ)?",
    roleKasir: "Thu ngân",
    roleDapur: "Bếp",
    roleLainnya: "Khác",
    staffTotal: "Đề xuất tổng cộng {n} tài khoản nhân viên (tự tạo trong menu Nhân viên sau khi đăng nhập — để bạn đặt email/mật khẩu cho từng người).",
    outletName: "Tên cửa hàng (hiển thị trên hóa đơn & trang đặt chỗ công khai)",
    ownerName: "Tên chủ cửa hàng",
    ownerEmail: "Email chủ (để đăng nhập)",
    googleNoPassword: "Đã xác minh qua Google — không cần mật khẩu, lần sau chỉ cần dùng nút \"Đăng nhập bằng Google\".",
    password: "Mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    reviewBusiness: "Cơ sở:",
    reviewOutlet: "Cửa hàng đầu tiên:",
    reviewBranches: "Số chi nhánh:",
    reviewUnits: "TV:",
    reviewUnitsValue: "{a} Android, {s} Smart TV, {g} TV thường (tổng {t})",
    reviewShift: "Ca:",
    reviewStaff: "Nhân viên:",
    reviewStaffValue: "{k} thu ngân, {d} bếp, {l} khác",
    reviewOwner: "Chủ:",
    reviewNote: "Khi đăng ký, một cửa hàng {branches}và một tài khoản Chủ sẽ được tạo ngay, kèm 30 ngày dùng thử miễn phí.",
    reviewBranchesExtra: "(+{n} chi nhánh) ",
    back: "Quay lại",
    next: "Tiếp tục",
    processing: "Đang xử lý...",
    submit: "Đăng ký ngay",
    consent: "Khi đăng ký, bạn đồng ý với {terms} và {privacy} của NEXBILL.",
    terms: "Điều khoản & Điều kiện",
    privacy: "Chính sách quyền riêng tư",
    haveAccount: "Đã có tài khoản?",
    loginHere: "Đăng nhập tại đây",
    catalogQuestion: "Muốn xem tất cả tính năng trước?",
    catalogLink: "Xem danh mục tính năng NEXBILL",
    errBusinessName: "Bắt buộc nhập tên cơ sở.",
    errOutletName: "Bắt buộc nhập tên cửa hàng.",
    errOwnerName: "Bắt buộc nhập tên chủ.",
    errEmail: "Email không hợp lệ.",
    errPasswordMin: "Mật khẩu tối thiểu 8 ký tự.",
    errPasswordMatch: "Xác nhận mật khẩu không khớp.",
    errRegister: "Đăng ký thất bại.",
    errTimeout: "Đăng ký mất nhiều thời gian hơn bình thường (máy chủ có thể đang bận). Vui lòng thử lại sau ít phút.",
    errNetwork: "Không kết nối được máy chủ. Kiểm tra internet và thử lại.",
    successTitle: "Đăng ký thành công 🎉",
    successBody: "Đã tạo cửa hàng {outlet}{branches}. 30 ngày dùng thử đã bắt đầu.",
    successBranches: " cùng {n} chi nhánh khác",
    recTitle: "Gợi ý dựa trên câu trả lời của bạn",
    recSmartPlug: "Số Smart Plug cần:",
    recSmartPlugNote: "(cho TV thường/Smart TV)",
    recPlan: "Gói gợi ý:",
    recPlanDetail: "Starter {starter}/tháng ({units} máy) · Pro {pro}/tháng (không giới hạn máy + mọi tính năng). Tự do chọn sau thời gian dùng thử.",
    recStaff: "Số tài khoản nhân viên nên tạo:",
    recStaffValue: "{n} tài khoản",
    recStaffNote: "(thu ngân/bếp/khác), cho {shifts} ca",
    successNote: "Bạn đã được đăng nhập. Tiếp tục đến trang Gói dịch vụ để chọn gói (Starter/Pro) và mua smart plug, hoặc vào thẳng Dashboard.",
    toBilling: "Đến trang Gói dịch vụ",
    toDashboard: "Đến Dashboard",
  },
};
