import { registerDict } from "./registry";

/**
 * Translations for /dashboard/shift — cashier shift open/close, physical cash
 * denomination counting, non-cash channel balance verification, and shift
 * history. Registered as a side effect on import; import this file from the
 * shift page before any component on that page calls useDashboardLang().t().
 */
registerDict({
  // --- Page header ---
  "shift.pageTitle": { id: "Shift & Kasir", en: "Shift & Cashier", ms: "Syif & Juruwang", th: "กะและแคชเชียร์", fil: "Shift at Cashier", vi: "Ca làm & Thu ngân" },
  "shift.pageSubtitle": { id: "Buka shift dengan modal awal, tutup dengan hitung fisik kas per pecahan — selisih terdeteksi otomatis, baru ditampilkan setelah hitungan disubmit.", en: "Open a shift with starting cash, close it by physically counting cash per denomination — variance is detected automatically and only shown after you submit the count.", ms: "Buka syif dengan modal permulaan, tutup dengan mengira fizikal tunai mengikut pecahan — perbezaan dikesan secara automatik dan hanya dipaparkan selepas kiraan dihantar.", th: "เปิดกะด้วยเงินทุนเริ่มต้น ปิดกะด้วยการนับเงินสดจริงตามมูลค่าธนบัตร/เหรียญ — ผลต่างจะถูกตรวจพบอัตโนมัติและแสดงหลังจากส่งการนับแล้วเท่านั้น", fil: "Magbukas ng shift gamit ang panimulang cash, isara ito sa pamamagitan ng pisikal na pagbibilang ng cash ayon sa denominasyon — awtomatikong nade-detect ang variance at ipapakita lang pagkatapos mong i-submit ang bilang.", vi: "Mở ca với tiền vốn ban đầu, đóng ca bằng cách đếm tiền mặt thực tế theo từng mệnh giá — chênh lệch được phát hiện tự động và chỉ hiển thị sau khi bạn gửi kết quả đếm." },
  "shift.staffLabel": { id: "Staf", en: "Staff", ms: "Staf", th: "พนักงาน", fil: "Staff", vi: "Nhân viên" },

  // --- Plain-language walkthrough card (for outlet staff unfamiliar with shift/cash-count terms) ---
  "shift.guideTitle": { id: "Panduan Singkat: Cara Kerja Shift", en: "Quick Guide: How Shifts Work", ms: "Panduan Ringkas: Cara Syif Berfungsi", th: "คู่มือฉบับย่อ: กะทำงานอย่างไร", fil: "Mabilisang Gabay: Paano Gumagana ang Shift", vi: "Hướng dẫn nhanh: Ca làm việc hoạt động thế nào" },
  "shift.guideStep1": { id: 'Di awal kerja, klik "Buka Shift" dan isi Modal Awal — jumlah uang tunai yang sudah ada di laci saat kamu mulai.', en: 'At the start of your shift, click "Open Shift" and enter the Starting Cash — the amount already in the drawer when you begin.', ms: 'Pada permulaan kerja, klik "Buka Syif" dan isi Modal Permulaan — jumlah wang tunai yang sudah ada dalam laci semasa anda mula.', th: 'ก่อนเริ่มงาน กดปุ่ม "เปิดกะ" แล้วกรอกเงินทุนเริ่มต้น — จำนวนเงินสดที่มีอยู่ในลิ้นชักตอนที่คุณเริ่มงาน', fil: 'Sa simula ng trabaho, i-click ang "Buksan ang Shift" at ilagay ang Panimulang Cash — ang halagang nasa drawer na kapag nagsimula ka.', vi: 'Đầu ca làm, nhấn "Mở ca" và nhập Tiền vốn ban đầu — số tiền mặt đã có sẵn trong ngăn kéo khi bạn bắt đầu.' },
  "shift.guideStep2": { id: "Selama shift berjalan, lakukan transaksi seperti biasa (rental, F&B, dll) — tidak perlu buka halaman ini lagi sampai mau pulang/gantian.", en: "During your shift, process transactions as usual (rentals, F&B, etc.) — no need to come back to this page until you're about to leave/hand over.", ms: "Semasa syif berjalan, buat urus niaga seperti biasa (sewa, F&B, dll) — tidak perlu buka halaman ini lagi sehingga anda mahu pulang/bertukar syif.", th: "ระหว่างกะทำงาน ให้ทำธุรกรรมตามปกติ (เช่าเครื่อง, F&B ฯลฯ) — ไม่ต้องเปิดหน้านี้อีกจนกว่าจะใกล้เลิกงาน/เปลี่ยนกะ", fil: "Habang tumatakbo ang shift, magproseso ng transaksyon gaya ng dati (rental, F&B, atbp.) — hindi na kailangang balikan ang page na ito hanggang sa aalis ka na/lilipat ng shift.", vi: "Trong suốt ca làm, xử lý giao dịch như bình thường (thuê máy, F&B, v.v.) — không cần quay lại trang này cho đến khi sắp về/bàn giao ca." },
  "shift.guideStep3": { id: 'Saat mau pulang atau gantian shift, buka halaman ini lagi dan klik "Tutup Shift".', en: 'When you\'re about to leave or hand over your shift, come back to this page and click "Close Shift".', ms: 'Apabila mahu pulang atau bertukar syif, buka semula halaman ini dan klik "Tutup Syif".', th: 'เมื่อใกล้เลิกงานหรือเปลี่ยนกะ ให้กลับมาที่หน้านี้แล้วกดปุ่ม "ปิดกะ"', fil: 'Kapag aalis ka na o lilipat ng shift, balikan ang page na ito at i-click ang "Isara ang Shift".', vi: 'Khi sắp về hoặc bàn giao ca, quay lại trang này và nhấn "Đóng ca".' },
  "shift.guideStep4": { id: "Hitung UANG TUNAI di laci satu per satu sesuai pecahannya (lembar Rp100.000, Rp50.000, dst), lalu isi jumlah lembarnya di kolom masing-masing — bukan totalnya, tapi JUMLAH LEMBAR/KEPINGnya.", en: "Count the CASH in the drawer one denomination at a time (Rp100,000 notes, Rp50,000 notes, etc.), then enter the note COUNT in each field — not the total value, the NUMBER OF NOTES/COINS.", ms: "Kira WANG TUNAI dalam laci satu demi satu mengikut pecahan (not Rp100,000, Rp50,000, dll), kemudian isi BILANGAN keping di setiap medan — bukan jumlah nilainya, tetapi BILANGAN kepingnya.", th: "นับ เงินสด ในลิ้นชักทีละมูลค่า (ธนบัตร Rp100,000, Rp50,000 ฯลฯ) แล้วกรอก จำนวนใบ ในแต่ละช่อง — ไม่ใช่มูลค่ารวม แต่เป็น จำนวนใบ/เหรียญ", fil: "Bilangin ang CASH sa drawer isa-isa ayon sa denominasyon (Rp100,000 na bill, Rp50,000, atbp.), pagkatapos ilagay ang BILANG ng piraso sa bawat field — hindi ang total value, kundi ang BILANG NG PIRASO.", vi: "Đếm TIỀN MẶT trong ngăn kéo từng mệnh giá một (tờ 100.000đ, 50.000đ, v.v.), rồi nhập SỐ LƯỢNG tờ vào từng ô — không phải tổng giá trị, mà là SỐ LƯỢNG tờ/xu." },
  "shift.guideStep5": { id: "Kalau ada channel non-tunai (GoPay, DANA, saldo Fastpay, dll), buka aplikasinya di HP, lihat angka saldo yang tertera di layar, lalu ketik angka itu apa adanya — jangan dikira-kira.", en: "If there are non-cash channels (GoPay, DANA, Fastpay balance, etc.), open their app on your phone, look at the balance number shown on screen, and type that exact number — don't estimate.", ms: "Jika terdapat saluran bukan tunai (GoPay, DANA, baki Fastpay, dll), buka aplikasinya di telefon, lihat angka baki yang dipaparkan pada skrin, kemudian taip angka itu dengan tepat — jangan anggarkan.", th: "หากมีช่องทางที่ไม่ใช่เงินสด (GoPay, DANA, ยอดคงเหลือ Fastpay ฯลฯ) ให้เปิดแอปในโทรศัพท์ ดูตัวเลขยอดคงเหลือที่แสดงบนหน้าจอ แล้วพิมพ์ตัวเลขนั้นตามจริง — อย่าประมาณ", fil: "Kung may mga non-cash na channel (GoPay, DANA, balanse sa Fastpay, atbp.), buksan ang app nito sa telepono, tingnan ang numero ng balanse na ipinapakita sa screen, at i-type nang eksakto ang numerong iyon — huwag magtantiya.", vi: "Nếu có kênh phi tiền mặt (GoPay, DANA, số dư Fastpay, v.v.), mở ứng dụng trên điện thoại, xem số dư hiển thị trên màn hình, rồi nhập đúng con số đó — đừng ước lượng." },
  "shift.guideStep6": { id: 'Klik "Tutup Shift". Sistem otomatis membandingkan hitunganmu dengan catatan transaksi, dan langsung menunjukkan kalau ada selisih (uang kurang atau lebih).', en: 'Click "Close Shift". The system automatically compares your count against the transaction records, and immediately shows if there\'s a variance (short or over).', ms: 'Klik "Tutup Syif". Sistem akan membandingkan kiraan anda dengan rekod urus niaga secara automatik, dan terus menunjukkan jika terdapat perbezaan (kurang atau lebih).', th: 'กดปุ่ม "ปิดกะ" ระบบจะเปรียบเทียบยอดที่คุณนับกับบันทึกธุรกรรมโดยอัตโนมัติ และแสดงผลทันทีหากมีส่วนต่าง (ขาดหรือเกิน)', fil: 'I-click ang "Isara ang Shift". Awtomatikong ikukumpara ng system ang bilang mo sa mga record ng transaksyon, at agad ipapakita kung may pagkakaiba (kulang o sobra).', vi: 'Nhấn "Đóng ca". Hệ thống sẽ tự động so sánh số bạn đếm với ghi nhận giao dịch, và hiển thị ngay nếu có chênh lệch (thiếu hoặc dư).' },

  // --- Deposit balance channels management ---
  "shift.depositChannelsTitle": { id: "Channel Saldo Deposit (Non-Tunai)", en: "Deposit Balance Channels (Non-Cash)", ms: "Saluran Baki Deposit (Bukan Tunai)", th: "ช่องทางยอดเงินฝาก (ไม่ใช่เงินสด)", fil: "Deposit Balance Channels (Non-Cash)", vi: "Kênh số dư ký quỹ (phi tiền mặt)" },
  "shift.depositChannelsDesc": { id: 'Daftar ini yang muncul di "Verifikasi Saldo Channel Non-Tunai" saat tutup shift — Saldo Deposit Fastpay (PPOB) bisa diganti namanya, dan kamu bisa menambah channel saldo deposit lain (mis. provider PPOB kedua). Setiap channel otomatis terhubung ke akun COA sendiri — tambah/hapus channel di sini akan ikut membuat/menghapus akun COA-nya.', en: 'This list is what shows up under "Non-Cash Channel Balance Verification" when closing a shift — Fastpay (PPOB) Deposit Balance can be renamed, and you can add other deposit-balance channels (e.g. a second PPOB provider). Each channel is automatically linked to its own COA account — adding/deleting a channel here also creates/removes its COA account.', ms: 'Senarai ini yang dipaparkan di "Pengesahan Baki Saluran Bukan Tunai" semasa menutup syif — Baki Deposit Fastpay (PPOB) boleh ditukar nama, dan anda boleh menambah saluran baki deposit lain (cth. pembekal PPOB kedua). Setiap saluran disambungkan secara automatik ke akaun COA sendiri — menambah/memadam saluran di sini turut mencipta/memadam akaun COA-nya.', th: 'รายการนี้จะปรากฏใน "ตรวจสอบยอดคงเหลือช่องทางที่ไม่ใช่เงินสด" ตอนปิดกะ — ยอดเงินฝาก Fastpay (PPOB) สามารถเปลี่ยนชื่อได้ และคุณสามารถเพิ่มช่องทางยอดเงินฝากอื่นได้ (เช่น ผู้ให้บริการ PPOB รายที่สอง) แต่ละช่องทางจะเชื่อมโยงกับบัญชี COA ของตัวเองโดยอัตโนมัติ — การเพิ่ม/ลบช่องทางที่นี่จะสร้าง/ลบบัญชี COA ไปพร้อมกันด้วย', fil: 'Ang listahang ito ang lumalabas sa "Beripikasyon ng Balanse ng Non-Cash Channel" kapag nagsasara ng shift — ang Deposit Balance ng Fastpay (PPOB) ay maaaring palitan ng pangalan, at maaari kang magdagdag ng ibang deposit-balance channel (hal. pangalawang PPOB provider). Bawat channel ay awtomatikong konektado sa sarili nitong account sa COA — ang pagdagdag/pagtanggal ng channel dito ay gagawa/magtatanggal din ng COA account nito.', vi: 'Danh sách này sẽ hiển thị trong mục "Xác minh số dư kênh phi tiền mặt" khi đóng ca — Số dư ký quỹ Fastpay (PPOB) có thể đổi tên, và bạn có thể thêm các kênh số dư ký quỹ khác (ví dụ nhà cung cấp PPOB thứ hai). Mỗi kênh sẽ tự động liên kết với một tài khoản COA riêng — thêm/xóa kênh ở đây cũng sẽ tạo/xóa tài khoản COA tương ứng.' },
  "shift.save": { id: "Simpan", en: "Save", ms: "Simpan", th: "บันทึก", fil: "I-save", vi: "Lưu" },
  "shift.cancel": { id: "Batal", en: "Cancel", ms: "Batal", th: "ยกเลิก", fil: "Kanselahin", vi: "Hủy" },
  "shift.systemBadge": { id: "Sistem", en: "System", ms: "Sistem", th: "ระบบ", fil: "System", vi: "Hệ thống" },
  "shift.rename": { id: "Ganti Nama", en: "Rename", ms: "Tukar Nama", th: "เปลี่ยนชื่อ", fil: "Palitan ang Pangalan", vi: "Đổi tên" },
  "shift.delete": { id: "Hapus", en: "Delete", ms: "Padam", th: "ลบ", fil: "Tanggalin", vi: "Xóa" },
  "shift.deleting": { id: "Menghapus...", en: "Deleting...", ms: "Memadam...", th: "กำลังลบ...", fil: "Tinatanggal...", vi: "Đang xóa..." },
  "shift.deleteTooltipReady": { id: "Hapus riwayat shift ini", en: "Delete this shift record", ms: "Padam rekod syif ini", th: "ลบประวัติกะนี้", fil: "Tanggalin ang record ng shift na ito", vi: "Xóa lịch sử ca này" },
  "shift.deleteTooltipNotClosed": { id: "Tutup shift ini dulu sebelum bisa dihapus", en: "Close this shift before it can be deleted", ms: "Tutup syif ini dahulu sebelum boleh dipadam", th: "ต้องปิดกะนี้ก่อนจึงจะลบได้", fil: "Isara muna ang shift na ito bago ito matanggal", vi: "Phải đóng ca này trước khi có thể xóa" },
  "shift.edit": { id: "Edit", en: "Edit", ms: "Edit", th: "แก้ไข", fil: "I-edit", vi: "Sửa" },
  "shift.editClose": { id: "Tutup", en: "Close", ms: "Tutup", th: "ปิด", fil: "Isara", vi: "Đóng" },
  "shift.editTooltip": { id: "Koreksi hitungan/saldo/catatan shift ini", en: "Correct this shift's counts/balances/notes", ms: "Betulkan kiraan/baki/nota syif ini", th: "แก้ไขยอดนับ/ยอดเงิน/บันทึกของกะนี้", fil: "Itama ang bilang/balanse/tala ng shift na ito", vi: "Sửa số đếm/số dư/ghi chú của ca này" },
  "shift.editLoading": { id: "Memuat detail shift...", en: "Loading shift detail...", ms: "Memuatkan butiran syif...", th: "กำลังโหลดรายละเอียดกะ...", fil: "Naglo-load ng detalye ng shift...", vi: "Đang tải chi tiết ca..." },
  "shift.editWarning": {
    id: "Koreksi ini akan mengubah angka final shift yang sudah ditutup — aktual kas & selisih dihitung ulang otomatis. Gunakan hanya untuk memperbaiki kesalahan input, bukan untuk sengaja menutupi selisih.",
    en: "This correction changes the final figures of an already-closed shift — actual cash & variance recalculate automatically. Use only to fix a data-entry mistake, not to deliberately cover up a variance.",
    ms: "Pembetulan ini akan menukar angka akhir syif yang sudah ditutup — kas sebenar & selisih dikira semula secara automatik. Guna hanya untuk membetulkan kesilapan input, bukan untuk sengaja menutup selisih.",
    th: "การแก้ไขนี้จะเปลี่ยนตัวเลขสุดท้ายของกะที่ปิดไปแล้ว — เงินสดจริงและส่วนต่างจะคำนวณใหม่อัตโนมัติ ใช้เพื่อแก้ไขข้อผิดพลาดในการป้อนข้อมูลเท่านั้น ไม่ใช่เพื่อปกปิดส่วนต่างโดยเจตนา",
    fil: "Babaguhin ng pagwawastong ito ang huling mga numero ng shift na nasara na — awtomatikong makukwenta ulit ang aktwal na cash at pagkakaiba. Gamitin lang ito para ayusin ang maling input, hindi para itago ang pagkakaiba.",
    vi: "Việc sửa này sẽ thay đổi số liệu cuối cùng của ca đã đóng — tiền mặt thực tế & chênh lệch sẽ tự tính lại. Chỉ dùng để sửa lỗi nhập liệu, không dùng để cố ý che giấu chênh lệch.",
  },
  "shift.saveEdit": { id: "Simpan Koreksi", en: "Save Correction", ms: "Simpan Pembetulan", th: "บันทึกการแก้ไข", fil: "I-save ang Pagwawasto", vi: "Lưu bản sửa" },
  "shift.editBalanceHint": {
    id: '"Ekspektasi" adalah saldo yang seharusnya ada menurut sistem (tidak ikut berubah kalau kamu edit) — kalau kamu ubah "Aktual", "Selisih" di sebelahnya otomatis dihitung ulang: Aktual dikurangi Ekspektasi.',
    en: '"Expected" is the balance the system says should be there (it doesn\'t change when you edit) — if you change "Actual", the "Variance" next to it recalculates automatically as Actual minus Expected.',
    ms: '"Jangkaan" ialah baki yang sepatutnya ada mengikut sistem (tidak berubah apabila anda edit) — jika anda ubah "Sebenar", "Perbezaan" di sebelahnya dikira semula secara automatik: Sebenar tolak Jangkaan.',
    th: '"คาดไว้" คือยอดที่ระบบคาดว่าควรมี (จะไม่เปลี่ยนเมื่อคุณแก้ไข) — ถ้าคุณเปลี่ยน "จริง" ตัว "ผลต่าง" ข้างๆ จะคำนวณใหม่อัตโนมัติ: จริงลบคาดไว้',
    fil: 'Ang "Inaasahan" ay ang balanseng dapat naroon ayon sa system (hindi ito nagbabago kapag nag-edit ka) — kapag binago mo ang "Aktwal", awtomatikong makukwenta ulit ang "Variance" sa tabi nito: Aktwal minus Inaasahan.',
    vi: '"Dự kiến" là số dư mà hệ thống cho là lẽ ra phải có (không đổi khi bạn sửa) — nếu bạn đổi "Thực tế", "Chênh lệch" bên cạnh sẽ tự tính lại: Thực tế trừ Dự kiến.',
  },
  "shift.savingEdit": { id: "Menyimpan...", en: "Saving...", ms: "Menyimpan...", th: "กำลังบันทึก...", fil: "Sine-save...", vi: "Đang lưu..." },
  "shift.newChannelPlaceholder": { id: "Nama channel saldo deposit baru, mis. Saldo Deposit Midtrans", en: "New deposit-balance channel name, e.g. Midtrans Deposit Balance", ms: "Nama saluran baki deposit baharu, cth. Baki Deposit Midtrans", th: "ชื่อช่องทางยอดเงินฝากใหม่ เช่น ยอดเงินฝาก Midtrans", fil: "Pangalan ng bagong deposit-balance channel, hal. Midtrans Deposit Balance", vi: "Tên kênh số dư ký quỹ mới, ví dụ Số dư ký quỹ Midtrans" },
  "shift.addChannel": { id: "Tambah Channel", en: "Add Channel", ms: "Tambah Saluran", th: "เพิ่มช่องทาง", fil: "Magdagdag ng Channel", vi: "Thêm kênh" },

  // --- Active shift / cash count ---
  "shift.activeShiftTitle": { id: "Shift Aktif", en: "Active Shift", ms: "Syif Aktif", th: "กะที่กำลังดำเนินการ", fil: "Aktibong Shift", vi: "Ca đang hoạt động" },
  "shift.runningSince": { id: "Berjalan sejak {time}", en: "Running since {time}", ms: "Berjalan sejak {time}", th: "ดำเนินการตั้งแต่ {time}", fil: "Tumatakbo simula {time}", vi: "Đang chạy từ {time}" },
  "shift.openingCashLabel": { id: "Modal awal:", en: "Starting cash:", ms: "Modal permulaan:", th: "เงินทุนเริ่มต้น:", fil: "Panimulang cash:", vi: "Tiền vốn ban đầu:" },
  "shift.cashCountTitle": { id: "Hitung Fisik Kas (Per Pecahan)", en: "Physical Cash Count (By Denomination)", ms: "Kiraan Fizikal Tunai (Mengikut Pecahan)", th: "การนับเงินสดจริง (แยกตามมูลค่า)", fil: "Pisikal na Bilang ng Cash (Ayon sa Denominasyon)", vi: "Kiểm đếm tiền mặt thực tế (theo mệnh giá)" },
  "shift.cashCountDesc": {
    id: 'Ambil semua uang tunai dari laci, pisahkan per jenis lembar/koin, lalu isi JUMLAH LEMBARNYA (bukan nilai rupiahnya) di kolom "Jumlah" masing-masing. Contoh: kalau ada 3 lembar Rp50.000, ketik "3" — bukan "150000". Sistem yang otomatis mengalikan dan menjumlahkan totalnya.',
    en: 'Take all the cash out of the drawer, sort it by note/coin type, then enter the COUNT of notes (not the rupiah value) in each "Amount" field. Example: 3 notes of Rp50,000 means typing "3" — not "150000". The system multiplies and totals it automatically.',
    ms: 'Keluarkan semua wang tunai dari laci, asingkan mengikut jenis not/syiling, kemudian isi BILANGAN kepingnya (bukan nilai ringgit) di setiap medan "Jumlah". Contoh: 3 keping Rp50,000 bermaksud taip "3" — bukan "150000". Sistem akan darab dan jumlahkan secara automatik.',
    th: 'นำเงินสดออกจากลิ้นชักทั้งหมด แยกตามประเภทธนบัตร/เหรียญ แล้วกรอก "จำนวนใบ" (ไม่ใช่มูลค่าเป็นเงิน) ในแต่ละช่อง ตัวอย่าง: ธนบัตร Rp50,000 จำนวน 3 ใบ ให้พิมพ์ "3" ไม่ใช่ "150000" ระบบจะคูณและรวมยอดให้อัตโนมัติ',
    fil: 'Kunin lahat ng cash sa drawer, ihiwalay ayon sa uri ng bill/barya, pagkatapos ilagay ang BILANG ng piraso (hindi ang halaga sa pera) sa bawat field na "Halaga". Halimbawa: 3 piraso ng Rp50,000 ay i-type na "3" — hindi "150000". Awtomatikong pararamihin at tutuusin ito ng system.',
    vi: 'Lấy hết tiền mặt ra khỏi ngăn kéo, phân loại theo từng mệnh giá tờ/xu, rồi nhập SỐ LƯỢNG tờ (không phải giá trị tiền) vào từng ô "Số lượng". Ví dụ: 3 tờ 50.000đ thì gõ "3" — không phải "150000". Hệ thống sẽ tự nhân và cộng tổng.',
  },
  "shift.qtyPlaceholder": { id: "Jumlah lembar", en: "Note count", ms: "Bilangan keping", th: "จำนวนใบ", fil: "Bilang ng piraso", vi: "Số lượng tờ" },
  "shift.qtyUnit": { id: "lbr", en: "pcs", ms: "keping", th: "ใบ", fil: "pc", vi: "tờ" },
  "shift.totalCountedLabel": { id: "Total Hitungan Fisik", en: "Physical Count Total", ms: "Jumlah Kiraan Fizikal", th: "ยอดรวมจากการนับจริง", fil: "Kabuuang Pisikal na Bilang", vi: "Tổng số đếm thực tế" },

  // --- Non-cash channel balance verification ---
  "shift.verifyBalanceTitle": { id: "Verifikasi Saldo Channel Non-Tunai", en: "Non-Cash Channel Balance Verification", ms: "Pengesahan Baki Saluran Bukan Tunai", th: "ตรวจสอบยอดคงเหลือช่องทางที่ไม่ใช่เงินสด", fil: "Beripikasyon ng Balanse ng Non-Cash Channel", vi: "Xác minh số dư kênh phi tiền mặt" },
  "shift.verifyBalanceDesc": {
    id: 'Buka aplikasi/HP masing-masing channel di bawah ini (GoPay Merchant, DANA Bisnis, dsb), lihat ANGKA SALDO yang tertera di layar utamanya saat ini, lalu ketik persis angka itu. Contoh: kalau di aplikasi GoPay tertulis saldo Rp350.000, ketik "350000". Jangan dikira-kira atau dibulatkan.',
    en: "Open each channel's app on your phone (GoPay Merchant, DANA Bisnis, etc.), look at the BALANCE NUMBER shown on its main screen right now, and type that exact number. Example: if GoPay's app shows a balance of Rp350,000, type \"350000\". Don't estimate or round it.",
    ms: 'Buka aplikasi setiap saluran di telefon anda (GoPay Merchant, DANA Bisnis, dll), lihat ANGKA BAKI yang dipaparkan pada skrin utamanya sekarang, kemudian taip angka tersebut dengan tepat. Contoh: jika aplikasi GoPay menunjukkan baki Rp350,000, taip "350000". Jangan anggarkan atau bundarkan.',
    th: 'เปิดแอปของแต่ละช่องทางในโทรศัพท์ของคุณ (GoPay Merchant, DANA Bisnis ฯลฯ) ดู "ตัวเลขยอดคงเหลือ" ที่แสดงบนหน้าจอหลักตอนนี้ แล้วพิมพ์ตัวเลขนั้นให้ตรงเป๊ะ ตัวอย่าง: ถ้าแอป GoPay แสดงยอด Rp350,000 ให้พิมพ์ "350000" อย่าประมาณหรือปัดเศษ',
    fil: 'Buksan ang app ng bawat channel sa iyong telepono (GoPay Merchant, DANA Bisnis, atbp.), tingnan ang NUMERO NG BALANSE na ipinapakita sa main screen nito ngayon, at i-type nang eksakto ang numerong iyon. Halimbawa: kung nagpapakita ang GoPay app ng balanseng Rp350,000, i-type ang "350000". Huwag magtantiya o bumilog.',
    vi: 'Mở ứng dụng của từng kênh trên điện thoại (GoPay Merchant, DANA Bisnis, v.v.), xem SỐ DƯ hiển thị trên màn hình chính lúc đó, rồi nhập đúng con số đó. Ví dụ: nếu ứng dụng GoPay hiển thị số dư 350.000đ, hãy gõ "350000". Đừng ước lượng hay làm tròn.',
  },
  "shift.balancePlaceholder": { id: "Saldo di app saat ini", en: "Current balance in app", ms: "Baki semasa dalam aplikasi", th: "ยอดคงเหลือปัจจุบันในแอป", fil: "Kasalukuyang balanse sa app", vi: "Số dư hiện tại trong ứng dụng" },

  // --- Notes + close/open shift actions ---
  "shift.notesLabel": { id: "Catatan (opsional)", en: "Notes (optional)", ms: "Nota (pilihan)", th: "หมายเหตุ (ไม่บังคับ)", fil: "Mga Tala (opsyonal)", vi: "Ghi chú (không bắt buộc)" },
  "shift.notesPlaceholder": { id: "Mis. alasan jika ada selisih yang sudah diketahui sebelumnya", en: "E.g. the reason if there's already a known variance", ms: "Cth. sebab jika terdapat perbezaan yang telah diketahui sebelum ini", th: "เช่น เหตุผลหากมีผลต่างที่ทราบอยู่แล้วก่อนหน้านี้", fil: "Hal. dahilan kung mayroon nang alam na variance", vi: "Ví dụ: lý do nếu đã biết trước có chênh lệch" },
  "shift.closing": { id: "Menutup...", en: "Closing...", ms: "Menutup...", th: "กำลังปิด...", fil: "Isinasara...", vi: "Đang đóng..." },
  "shift.closeShiftBtn": { id: "Tutup Shift", en: "Close Shift", ms: "Tutup Syif", th: "ปิดกะ", fil: "Isara ang Shift", vi: "Đóng ca" },
  "shift.openNewShiftTitle": { id: "Buka Shift Baru", en: "Open New Shift", ms: "Buka Syif Baharu", th: "เปิดกะใหม่", fil: "Magbukas ng Bagong Shift", vi: "Mở ca mới" },
  "shift.openingCashPlaceholder": { id: "Modal awal kas", en: "Starting cash amount", ms: "Jumlah modal permulaan tunai", th: "จำนวนเงินทุนเริ่มต้น", fil: "Halaga ng panimulang cash", vi: "Số tiền vốn ban đầu" },
  "shift.openShiftBtn": { id: "Buka Shift", en: "Open Shift", ms: "Buka Syif", th: "เปิดกะ", fil: "Buksan ang Shift", vi: "Mở ca" },

  // --- Close summary reveal ---
  "shift.closeSummaryTitle": { id: "Ringkasan Tutup Shift", en: "Shift Close Summary", ms: "Ringkasan Penutupan Syif", th: "สรุปการปิดกะ", fil: "Buod ng Pagsasara ng Shift", vi: "Tóm tắt đóng ca" },
  "shift.downloadReportBtn": { id: "Download Berita Acara (PDF)", en: "Download Handover Report (PDF)", ms: "Muat Turun Laporan Serah Terima (PDF)", th: "ดาวน์โหลดรายงานส่งมอบ (PDF)", fil: "I-download ang Ulat ng Paghahanda (PDF)", vi: "Tải biên bản bàn giao (PDF)" },
  "shift.cashInLabel": { id: "Kas Masuk", en: "Cash In", ms: "Tunai Masuk", th: "เงินสดเข้า", fil: "Cash In", vi: "Tiền vào" },
  "shift.cashOutLabel": { id: "Kas Keluar", en: "Cash Out", ms: "Tunai Keluar", th: "เงินสดออก", fil: "Cash Out", vi: "Tiền ra" },
  "shift.expectedCashLabel": { id: "Ekspektasi Kas", en: "Expected Cash", ms: "Jangkaan Tunai", th: "เงินสดที่คาดไว้", fil: "Inaasahang Cash", vi: "Tiền mặt dự kiến" },
  "shift.expectedCashHint": { id: "Uang yang SEHARUSNYA ada di laci menurut catatan transaksi sistem (modal awal + uang masuk − uang keluar) — bukan hasil hitungan fisikmu.", en: "The amount that SHOULD be in the drawer according to the system's transaction records (starting cash + cash in − cash out) — not your physical count.", ms: "Jumlah yang SEPATUTNYA ada dalam laci mengikut rekod transaksi sistem (modal permulaan + tunai masuk − tunai keluar) — bukan hasil kiraan fizikal anda.", th: "จำนวนที่ควรมีในลิ้นชักตามบันทึกธุรกรรมของระบบ (เงินทุนเริ่มต้น + เงินเข้า − เงินออก) — ไม่ใช่ผลจากการนับจริงของคุณ", fil: "Ang halagang DAPAT nasa drawer batay sa record ng transaksyon ng system (panimulang cash + cash in − cash out) — hindi ang resulta ng pisikal mong bilang.", vi: "Số tiền LẼ RA phải có trong ngăn kéo theo ghi nhận giao dịch của hệ thống (vốn ban đầu + tiền vào − tiền ra) — không phải kết quả đếm thực tế của bạn." },
  "shift.cashVarianceLabel": { id: "Selisih Kas", en: "Cash Variance", ms: "Perbezaan Tunai", th: "ผลต่างเงินสด", fil: "Variance ng Cash", vi: "Chênh lệch tiền mặt" },
  "shift.cashVarianceHint": { id: "Selisih = uang hasil hitungan fisikmu dikurangi Ekspektasi Kas. Negatif berarti uang di laci kurang dari seharusnya; positif berarti lebih.", en: "Variance = your physical count minus Expected Cash. Negative means the drawer has less than it should; positive means more.", ms: "Perbezaan = hasil kiraan fizikal anda tolak Jangkaan Tunai. Negatif bermaksud wang dalam laci kurang daripada sepatutnya; positif bermaksud lebih.", th: "ผลต่าง = ยอดนับจริงของคุณลบด้วยเงินสดที่คาดไว้ ค่าติดลบหมายถึงเงินในลิ้นชักน้อยกว่าที่ควร ค่าบวกหมายถึงมากกว่า", fil: "Variance = pisikal mong bilang minus ang Inaasahang Cash. Negative ay nangangahulugang kulang ang laman ng drawer sa dapat; positive ay sobra.", vi: "Chênh lệch = số đếm thực tế trừ Tiền mặt dự kiến. Âm nghĩa là ngăn kéo có ít hơn mức lẽ ra phải có; dương nghĩa là nhiều hơn." },
  "shift.shortSuffixLower": { id: " (kurang)", en: " (short)", ms: " (kurang)", th: " (ขาด)", fil: " (kulang)", vi: " (thiếu)" },
  "shift.overSuffixLower": { id: " (lebih)", en: " (over)", ms: " (lebih)", th: " (เกิน)", fil: " (sobra)", vi: " (dư)" },
  "shift.varianceShort": { id: "(Kurang)", en: "(Short)", ms: "(Kurang)", th: "(ขาด)", fil: "(Kulang)", vi: "(Thiếu)" },
  "shift.varianceOver": { id: "(Lebih)", en: "(Over)", ms: "(Lebih)", th: "(เกิน)", fil: "(Sobra)", vi: "(Dư)" },
  "shift.colChannel": { id: "Channel", en: "Channel", ms: "Saluran", th: "ช่องทาง", fil: "Channel", vi: "Kênh" },
  "shift.colExpected": { id: "Ekspektasi", en: "Expected", ms: "Jangkaan", th: "คาดไว้", fil: "Inaasahan", vi: "Dự kiến" },
  "shift.colExpectedHint": { id: "Saldo yang seharusnya ada menurut sistem", en: "The balance that should be there according to the system", ms: "Baki yang sepatutnya ada mengikut sistem", th: "ยอดคงเหลือที่ควรมีตามระบบ", fil: "Ang balanseng dapat naroon ayon sa system", vi: "Số dư lẽ ra phải có theo hệ thống" },
  "shift.colActual": { id: "Aktual", en: "Actual", ms: "Sebenar", th: "จริง", fil: "Aktwal", vi: "Thực tế" },
  "shift.colActualHint": { id: "Saldo yang kamu lihat di aplikasi channel tersebut", en: "The balance you saw in that channel's app", ms: "Baki yang anda lihat dalam aplikasi saluran tersebut", th: "ยอดคงเหลือที่คุณเห็นในแอปของช่องทางนั้น", fil: "Ang balanseng nakita mo sa app ng channel na iyon", vi: "Số dư bạn thấy trong ứng dụng của kênh đó" },
  "shift.colActualCashHint": { id: "Total uang tunai hasil hitungan fisik saat tutup shift", en: "Total cash from the physical count when the shift was closed", ms: "Jumlah wang tunai daripada kiraan fizikal semasa syif ditutup", th: "ยอดเงินสดรวมจากการนับจริงตอนปิดกะ", fil: "Kabuuang cash mula sa pisikal na bilang noong isinara ang shift", vi: "Tổng tiền mặt từ lần đếm thực tế khi đóng ca" },
  "shift.colVariance": { id: "Selisih", en: "Variance", ms: "Perbezaan", th: "ผลต่าง", fil: "Variance", vi: "Chênh lệch" },
  "shift.colVarianceHint": { id: "Aktual dikurangi Ekspektasi", en: "Actual minus Expected", ms: "Sebenar tolak Jangkaan", th: "จริงลบคาดไว้", fil: "Aktwal minus Inaasahan", vi: "Thực tế trừ Dự kiến" },

  // --- Shift history ---
  "shift.historyTitle": { id: "Riwayat Shift", en: "Shift History", ms: "Sejarah Syif", th: "ประวัติกะ", fil: "Kasaysayan ng Shift", vi: "Lịch sử ca" },
  "shift.historyDescPrefix": { id: "Setiap pergantian shift otomatis dicek selisih kas (fisik vs ekspektasi sistem) dan selisih saldo channel non-tunai — ditandai", en: "Every shift change automatically checks the cash variance (physical vs. system expectation) and the non-cash channel balance variance — flagged", ms: "Setiap pertukaran syif secara automatik menyemak perbezaan tunai (fizikal berbanding jangkaan sistem) dan perbezaan baki saluran bukan tunai — ditanda", th: "ทุกครั้งที่เปลี่ยนกะ ระบบจะตรวจสอบผลต่างเงินสด (เงินจริงเทียบกับที่ระบบคาดไว้) และผลต่างยอดคงเหลือช่องทางที่ไม่ใช่เงินสดโดยอัตโนมัติ — ทำเครื่องหมายเป็น", fil: "Bawat pagpapalit ng shift ay awtomatikong sinusuri ang variance ng cash (pisikal kumpara sa inaasahan ng system) at variance ng balanse ng non-cash channel — minarkahan", vi: "Mỗi lần đổi ca, hệ thống tự động kiểm tra chênh lệch tiền mặt (thực tế so với dự kiến của hệ thống) và chênh lệch số dư kênh phi tiền mặt — được đánh dấu" },
  "shift.historyDescRedLabel": { id: 'merah "Kurang"', en: 'red "Short"', ms: 'merah "Kurang"', th: 'สีแดง "ขาด"', fil: 'pulang "Kulang"', vi: 'màu đỏ "Thiếu"' },
  "shift.historyDescMiddle": { id: "untuk kekurangan dan", en: "for a shortage and", ms: "untuk kekurangan dan", th: "สำหรับกรณีขาด และ", fil: "para sa kakulangan at", vi: "cho trường hợp thiếu và" },
  "shift.historyDescAmberLabel": { id: 'kuning "Lebih"', en: 'amber "Over"', ms: 'kuning "Lebih"', th: 'สีเหลือง "เกิน"', fil: 'dilaw "Sobra"', vi: 'màu hổ phách "Dư"' },
  "shift.historyDescSuffix": { id: "untuk kelebihan, supaya keduanya sama-sama kelihatan, bukan cuma yang kurang.", en: "for an overage, so both are equally visible, not just shortages.", ms: "untuk kelebihan, supaya kedua-duanya sama-sama kelihatan, bukan hanya kekurangan.", th: "สำหรับกรณีเกิน เพื่อให้มองเห็นทั้งสองกรณีเท่าๆ กัน ไม่ใช่แค่กรณีที่ขาด", fil: "para sa sobra, para pareho itong makikita, hindi lang ang kakulangan.", vi: "cho trường hợp dư, để cả hai trường hợp đều dễ nhìn thấy, không chỉ riêng phần thiếu." },
  "shift.colOpen": { id: "Buka", en: "Opened", ms: "Dibuka", th: "เปิด", fil: "Binuksan", vi: "Mở" },
  "shift.colClose": { id: "Tutup", en: "Closed", ms: "Ditutup", th: "ปิด", fil: "Isinara", vi: "Đóng" },
  "shift.colStaff": { id: "Karyawan", en: "Employee", ms: "Kakitangan", th: "พนักงาน", fil: "Empleyado", vi: "Nhân viên" },
  "shift.colOpeningCapital": { id: "Modal", en: "Starting Cash", ms: "Modal", th: "เงินทุน", fil: "Panimulang Cash", vi: "Vốn" },
  "shift.colNonCashVariance": { id: "Selisih Non-Tunai", en: "Non-Cash Variance", ms: "Perbezaan Bukan Tunai", th: "ผลต่างที่ไม่ใช่เงินสด", fil: "Variance ng Non-Cash", vi: "Chênh lệch phi tiền mặt" },
  "shift.colNonCashVarianceHint": { id: "Total selisih (aktual vs ekspektasi) untuk semua channel non-tunai seperti GoPay/DANA/Fastpay pada shift ini", en: "Total variance (actual vs. expected) across all non-cash channels like GoPay/DANA/Fastpay for this shift", ms: "Jumlah perbezaan (sebenar berbanding jangkaan) untuk semua saluran bukan tunai seperti GoPay/DANA/Fastpay pada syif ini", th: "ผลต่างรวม (จริงเทียบกับที่คาดไว้) ของทุกช่องทางที่ไม่ใช่เงินสด เช่น GoPay/DANA/Fastpay ในกะนี้", fil: "Kabuuang variance (aktwal kumpara sa inaasahan) sa lahat ng non-cash channel tulad ng GoPay/DANA/Fastpay sa shift na ito", vi: "Tổng chênh lệch (thực tế so với dự kiến) trên tất cả các kênh phi tiền mặt như GoPay/DANA/Fastpay trong ca này" },
  "shift.pdfLink": { id: "PDF", en: "PDF", ms: "PDF", th: "PDF", fil: "PDF", vi: "PDF" },
  "shift.colFraud": { id: "Anti-Fraud", en: "Anti-Fraud", ms: "Anti-Fraud", th: "ป้องกันทุจริต", fil: "Anti-Fraud", vi: "Chống gian lận" },
  "shift.colFraudHint": { id: "Ditandai otomatis kalau selisih atau jumlah void/refund/hapus pada shift ini melebihi ambang batas di Pengaturan > Preferensi", en: "Auto-flagged when this shift's variance or void/refund/delete count exceeds the threshold in Settings > Preferences", ms: "Ditanda secara automatik jika perbezaan atau bilangan void/refund/padam syif ini melebihi ambang di Tetapan > Keutamaan", th: "ถูกตั้งค่าสถานะอัตโนมัติเมื่อผลต่างหรือจำนวนการยกเลิก/คืนเงิน/ลบของกะนี้เกินเกณฑ์ที่ตั้งไว้ในการตั้งค่า > การตั้งค่าที่ต้องการ", fil: "Awtomatikong minarkahan kapag ang variance o bilang ng void/refund/delete sa shift na ito ay lumampas sa threshold sa Settings > Preferences", vi: "Tự động gắn cờ khi chênh lệch hoặc số lần hủy/hoàn tiền/xóa của ca này vượt ngưỡng trong Cài đặt > Tùy chọn" },
  "shift.fraud.clean": { id: "Bersih", en: "Clean", ms: "Bersih", th: "ปกติ", fil: "Malinis", vi: "Sạch" },
  "shift.fraud.flaggedCount": { id: "{count} ditandai", en: "{count} flagged", ms: "{count} ditanda", th: "ถูกตั้งค่าสถานะ {count}", fil: "{count} minarkahan", vi: "{count} bị gắn cờ" },
  "shift.fraud.pendingReview": { id: "Menunggu review", en: "Awaiting review", ms: "Menunggu semakan", th: "รอตรวจสอบ", fil: "Naghihintay ng review", vi: "Chờ xem xét" },
  "shift.fraud.approveBtn": { id: "Setujui", en: "Approve", ms: "Luluskan", th: "อนุมัติ", fil: "Aprubahan", vi: "Duyệt" },
  "shift.fraud.rejectBtn": { id: "Tolak", en: "Reject", ms: "Tolak", th: "ปฏิเสธ", fil: "Tanggihan", vi: "Từ chối" },
  "shift.fraud.reviewed": { id: "Sudah ditinjau", en: "Reviewed", ms: "Telah disemak", th: "ตรวจสอบแล้ว", fil: "Na-review na", vi: "Đã xem xét" },
  "shift.fraud.reviewRejected": { id: "Ditolak reviewer", en: "Rejected by reviewer", ms: "Ditolak oleh penyemak", th: "ผู้ตรวจสอบปฏิเสธ", fil: "Tinanggihan ng reviewer", vi: "Người xem xét đã từ chối" },
  "shift.review.rejectNotePrompt": { id: "Catatan penolakan (opsional)?", en: "Rejection note (optional)?", ms: "Catatan penolakan (pilihan)?", th: "หมายเหตุการปฏิเสธ (ไม่บังคับ)?", fil: "Tala ng pagtanggi (opsyonal)?", vi: "Ghi chú từ chối (không bắt buộc)?" },

  // --- Alerts / confirms ---
  "shift.confirmDeleteChannel": { id: 'Hapus channel "{label}"? Akun COA yang terkait akan otomatis dihapus/diarsipkan bersamaan.', en: 'Delete channel "{label}"? Its linked COA account will be automatically deleted/archived along with it.', ms: 'Padam saluran "{label}"? Akaun COA yang berkaitan akan dipadam/diarkibkan secara automatik bersama-sama.', th: 'ลบช่องทาง "{label}" หรือไม่? บัญชี COA ที่เกี่ยวข้องจะถูกลบ/เก็บถาวรโดยอัตโนมัติไปพร้อมกัน', fil: 'Tanggalin ang channel na "{label}"? Awtomatikong matatanggal/ma-archive ang kaugnay na COA account kasabay nito.', vi: 'Xóa kênh "{label}"? Tài khoản COA liên kết sẽ tự động bị xóa/lưu trữ cùng lúc.' },
  "shift.confirmDeleteShift": { id: "Hapus riwayat shift ini (dibuka {openedAt}, kasir {staffName})? Tidak bisa dibatalkan.", en: "Delete this shift record (opened {openedAt}, cashier {staffName})? This cannot be undone.", ms: "Padam rekod syif ini (dibuka {openedAt}, juruwang {staffName})? Ini tidak boleh dibatalkan.", th: "ลบประวัติกะนี้ (เปิดเมื่อ {openedAt} แคชเชียร์ {staffName}) หรือไม่? ไม่สามารถยกเลิกได้", fil: "Tanggalin ang record ng shift na ito (binuksan {openedAt}, cashier {staffName})? Hindi na ito maibabalik.", vi: "Xóa lịch sử ca này (mở lúc {openedAt}, thu ngân {staffName})? Không thể hoàn tác." },
  "shift.confirmDeleteOpenShift": {
    id: "PERHATIAN: shift ini MASIH BERJALAN (dibuka {openedAt}, kasir {staffName}), belum ditutup. Menghapusnya akan langsung menghilangkannya dari sistem — kasir yang memakainya akan diminta buka shift baru, dan transaksi yang sudah tercatat di shift ini kehilangan tautannya. Hanya lakukan ini untuk shift yang memang error/tidak akan pernah ditutup normal. Lanjutkan hapus?",
    en: "WARNING: this shift is STILL RUNNING (opened {openedAt}, cashier {staffName}), not yet closed. Deleting it removes it from the system immediately — the cashier using it will be prompted to open a new shift, and transactions already tagged to this shift lose that link. Only do this for a shift that's genuinely broken/will never be closed normally. Continue deleting?",
    ms: "AMARAN: syif ini MASIH BERJALAN (dibuka {openedAt}, juruwang {staffName}), belum ditutup. Memadamnya akan terus menghilangkannya dari sistem — juruwang yang menggunakannya akan diminta membuka syif baharu, dan transaksi yang sudah ditandakan pada syif ini kehilangan pautan tersebut. Lakukan ini hanya untuk syif yang memang rosak/tidak akan pernah ditutup secara normal. Teruskan padam?",
    th: "คำเตือน: กะนี้ยังดำเนินการอยู่ (เปิดเมื่อ {openedAt} แคชเชียร์ {staffName}) ยังไม่ได้ปิด การลบจะทำให้หายไปจากระบบทันที — แคชเชียร์ที่ใช้งานอยู่จะถูกขอให้เปิดกะใหม่ และธุรกรรมที่บันทึกไว้ในกะนี้จะสูญเสียการเชื่อมโยง ทำเช่นนี้เฉพาะกะที่ผิดพลาดจริงๆ/จะไม่มีวันถูกปิดตามปกติเท่านั้น ดำเนินการลบต่อหรือไม่?",
    fil: "BABALA: ang shift na ito ay TUMATAKBO PA (binuksan {openedAt}, cashier {staffName}), hindi pa isinara. Ang pagtanggal nito ay agad itong aalisin sa system — ang cashier na gumagamit nito ay hihilingin na magbukas ng bagong shift, at mawawala ang link ng mga transaksyong naka-tag na sa shift na ito. Gawin lang ito kung talagang sira ang shift/hindi na ito maisasara nang normal. Ituloy ang pagtanggal?",
    vi: "CẢNH BÁO: ca này VẪN ĐANG CHẠY (mở lúc {openedAt}, thu ngân {staffName}), chưa đóng. Xóa nó sẽ loại bỏ ngay khỏi hệ thống — thu ngân đang dùng ca này sẽ được yêu cầu mở ca mới, và các giao dịch đã gắn với ca này sẽ mất liên kết đó. Chỉ làm điều này với ca thực sự bị lỗi/sẽ không bao giờ đóng bình thường được. Tiếp tục xóa?",
  },
  "shift.deleteTooltipStillOpen": { id: "Shift ini masih berjalan — hapus hanya kalau memang shift error/tidak akan ditutup normal", en: "This shift is still running — only delete if it's genuinely broken/won't be closed normally", ms: "Syif ini masih berjalan — padam hanya jika ia memang rosak/tidak akan ditutup secara normal", th: "กะนี้ยังดำเนินการอยู่ — ลบเฉพาะเมื่อผิดพลาดจริงๆ/จะไม่ถูกปิดตามปกติ", fil: "Tumatakbo pa ang shift na ito — tanggalin lang kung talagang sira/hindi na isasara nang normal", vi: "Ca này vẫn đang chạy — chỉ xóa nếu thực sự bị lỗi/sẽ không đóng bình thường được" },
  "shift.missingBalanceAlert": { id: "Saldo aktual belum diisi untuk: {list}", en: "Actual balance not yet filled in for: {list}", ms: "Baki sebenar belum diisi untuk: {list}", th: "ยังไม่ได้กรอกยอดคงเหลือจริงสำหรับ: {list}", fil: "Hindi pa napunan ang aktwal na balanse para sa: {list}", vi: "Chưa nhập số dư thực tế cho: {list}" },
  "shift.confirmCloseShift": { id: "Pastikan hitungan fisik sudah final sebelum submit — setelah ini tidak bisa diubah. Lanjutkan tutup shift?", en: "Make sure the physical count is final before submitting — it can't be changed after this. Continue closing the shift?", ms: "Pastikan kiraan fizikal sudah muktamad sebelum menghantar — selepas ini tidak boleh diubah. Teruskan menutup syif?", th: "ตรวจสอบให้แน่ใจว่าการนับจริงเป็นค่าสุดท้ายก่อนส่ง — หลังจากนี้จะไม่สามารถแก้ไขได้ ต้องการปิดกะต่อหรือไม่?", fil: "Siguraduhing final na ang pisikal na bilang bago mag-submit — hindi na ito mababago pagkatapos nito. Ituloy ang pagsasara ng shift?", vi: "Đảm bảo số đếm thực tế là số liệu cuối cùng trước khi gửi — sau bước này sẽ không thể thay đổi. Tiếp tục đóng ca?" },
});
