import { registerDict } from "./registry";

/** Hapus akun & data (Pengaturan → Akun Saya), lihat src/lib/account-deletion. */
registerDict({
  "delAcc.heading": { id: "Hapus Akun & Data", en: "Delete Account & Data", ms: "Padam Akaun & Data", th: "ลบบัญชีและข้อมูล", fil: "Burahin ang Account at Data", vi: "Xóa tài khoản & dữ liệu" },
  "delAcc.desc": { id: "Menghapus akun Owner ini beserta data outlet: {outlets}. Akun, staf, dan outlet langsung dinonaktifkan; data pribadi dihapus atau dianonimkan paling lambat 30 hari kemudian. Catatan transaksi dan invoice yang wajib disimpan menurut hukum tetap disimpan tanpa identitas.", en: "Deletes this Owner account and the outlet data for: {outlets}. The account, staff, and outlets are deactivated immediately; personal data is deleted or anonymised within 30 days. Transaction records and invoices that the law requires us to keep are retained without identities.", ms: "Memadam akaun Owner ini serta data outlet: {outlets}. Akaun, staf dan outlet terus dinyahaktifkan; data peribadi dipadam atau dianonimkan selewat-lewatnya 30 hari kemudian. Rekod transaksi dan invois yang wajib disimpan mengikut undang-undang dikekalkan tanpa identiti.", th: "ลบบัญชี Owner นี้พร้อมข้อมูลสาขา: {outlets} บัญชี พนักงาน และสาขาจะถูกปิดใช้งานทันที ข้อมูลส่วนบุคคลจะถูกลบหรือทำให้ไม่ระบุตัวตนภายใน 30 วัน บันทึกธุรกรรมและใบแจ้งหนี้ที่กฎหมายกำหนดให้เก็บจะถูกเก็บไว้โดยไม่มีข้อมูลระบุตัวตน", fil: "Buburahin ang Owner account na ito pati ang data ng outlet: {outlets}. Agad na idi-deactivate ang account, staff, at outlet; buburahin o gagawing anonymous ang personal data sa loob ng 30 araw. Ang mga transaksyon at invoice na kailangang itago ayon sa batas ay itatago nang walang pagkakakilanlan.", vi: "Xóa tài khoản Owner này cùng dữ liệu cơ sở: {outlets}. Tài khoản, nhân viên và cơ sở bị vô hiệu hóa ngay; dữ liệu cá nhân được xóa hoặc ẩn danh trong vòng 30 ngày. Hồ sơ giao dịch và hóa đơn mà pháp luật yêu cầu lưu giữ sẽ được giữ lại mà không có thông tin định danh." },
  "delAcc.notOwner": { id: "Hanya Owner yang bisa menghapus akun & data outlet. Minta Owner menghapus akses Anda di menu Staf & Hak Akses.", en: "Only the Owner can delete the account & outlet data. Ask your Owner to remove your access in Staff & Permissions.", ms: "Hanya Owner boleh memadam akaun & data outlet. Minta Owner membuang akses anda di menu Staf & Hak Akses.", th: "เฉพาะ Owner เท่านั้นที่ลบบัญชีและข้อมูลสาขาได้ ขอให้ Owner ลบสิทธิ์ของคุณในเมนูพนักงานและสิทธิ์", fil: "Owner lang ang makakapagbura ng account at data ng outlet. Hilingin sa Owner na alisin ang access mo sa Staff at Permissions.", vi: "Chỉ Owner mới có thể xóa tài khoản & dữ liệu cơ sở. Hãy nhờ Owner gỡ quyền truy cập của bạn trong mục Nhân viên & Quyền." },
  "delAcc.exportHint": { id: "Sebelum menghapus, unduh laporan yang Anda perlukan dari menu Laporan dan Akuntansi.", en: "Before deleting, download any reports you need from Reports and Accounting.", ms: "Sebelum memadam, muat turun laporan yang anda perlukan dari menu Laporan dan Perakaunan.", th: "ก่อนลบ ให้ดาวน์โหลดรายงานที่ต้องการจากเมนูรายงานและบัญชี", fil: "Bago magbura, i-download ang mga report na kailangan mo mula sa Reports at Accounting.", vi: "Trước khi xóa, hãy tải các báo cáo bạn cần từ mục Báo cáo và Kế toán." },
  "delAcc.reasonLabel": { id: "Alasan (opsional)", en: "Reason (optional)", ms: "Sebab (pilihan)", th: "เหตุผล (ไม่บังคับ)", fil: "Dahilan (opsyonal)", vi: "Lý do (không bắt buộc)" },
  "delAcc.requestButton": { id: "Kirim Kode Konfirmasi", en: "Send Confirmation Code", ms: "Hantar Kod Pengesahan", th: "ส่งรหัสยืนยัน", fil: "Ipadala ang Confirmation Code", vi: "Gửi mã xác nhận" },
  "delAcc.codeSent": { id: "Kode 6 digit dikirim ke {email}. Berlaku 15 menit.", en: "A 6-digit code was sent to {email}. Valid for 15 minutes.", ms: "Kod 6 digit dihantar ke {email}. Sah selama 15 minit.", th: "ส่งรหัส 6 หลักไปที่ {email} แล้ว ใช้ได้ 15 นาที", fil: "May 6-digit code na ipinadala sa {email}. Valid nang 15 minuto.", vi: "Mã 6 chữ số đã được gửi tới {email}. Hiệu lực 15 phút." },
  "delAcc.codeLabel": { id: "Kode dari email", en: "Code from email", ms: "Kod daripada e-mel", th: "รหัสจากอีเมล", fil: "Code mula sa email", vi: "Mã trong email" },
  "delAcc.phraseLabel": { id: "Ketik HAPUS untuk mengonfirmasi", en: "Type HAPUS to confirm", ms: "Taip HAPUS untuk mengesahkan", th: "พิมพ์ HAPUS เพื่อยืนยัน", fil: "I-type ang HAPUS para kumpirmahin", vi: "Gõ HAPUS để xác nhận" },
  "delAcc.confirmButton": { id: "Hapus Akun Permanen", en: "Delete Account Permanently", ms: "Padam Akaun Secara Kekal", th: "ลบบัญชีถาวร", fil: "Burahin ang Account nang Permanente", vi: "Xóa tài khoản vĩnh viễn" },
  "delAcc.cancelButton": { id: "Batalkan", en: "Cancel", ms: "Batal", th: "ยกเลิก", fil: "Kanselahin", vi: "Hủy" },
  "delAcc.resend": { id: "Kirim ulang kode", en: "Resend code", ms: "Hantar semula kod", th: "ส่งรหัสอีกครั้ง", fil: "Ipadala muli ang code", vi: "Gửi lại mã" },
  "delAcc.confirmDialog": { id: "Yakin? Akun dan semua outlet di atas langsung dinonaktifkan dan Anda akan keluar dari NEXBILL.", en: "Are you sure? The account and all outlets above will be deactivated immediately and you will be signed out.", ms: "Pasti? Akaun dan semua outlet di atas terus dinyahaktifkan dan anda akan dilog keluar.", th: "แน่ใจหรือไม่? บัญชีและสาขาทั้งหมดข้างต้นจะถูกปิดใช้งานทันทีและคุณจะออกจากระบบ", fil: "Sigurado ka ba? Agad na idi-deactivate ang account at lahat ng outlet sa itaas at ila-log out ka.", vi: "Bạn chắc chứ? Tài khoản và mọi cơ sở ở trên sẽ bị vô hiệu hóa ngay và bạn sẽ bị đăng xuất." },
  "delAcc.done": { id: "Akun dinonaktifkan. Data dihapus paling lambat {date}. Untuk membatalkan, hubungi sales@nexbill.id sebelum tanggal itu.", en: "The account has been deactivated. Data will be deleted by {date}. To cancel, contact sales@nexbill.id before that date.", ms: "Akaun telah dinyahaktifkan. Data dipadam selewat-lewatnya {date}. Untuk membatalkan, hubungi sales@nexbill.id sebelum tarikh itu.", th: "ปิดใช้งานบัญชีแล้ว ข้อมูลจะถูกลบภายใน {date} หากต้องการยกเลิก ติดต่อ sales@nexbill.id ก่อนวันดังกล่าว", fil: "Na-deactivate na ang account. Buburahin ang data hanggang {date}. Para kanselahin, kontakin ang sales@nexbill.id bago ang petsang iyon.", vi: "Tài khoản đã bị vô hiệu hóa. Dữ liệu sẽ bị xóa trước {date}. Để hủy, liên hệ sales@nexbill.id trước ngày đó." },
  "delAcc.privacyLink": { id: "Kebijakan Privasi", en: "Privacy Policy", ms: "Dasar Privasi", th: "นโยบายความเป็นส่วนตัว", fil: "Patakaran sa Privacy", vi: "Chính sách quyền riêng tư" },

  // --- Teks yang sebelumnya ditulis langsung di kode (audit i18n) ---
  "delAcc.requestFailed": { id: "Gagal mengirim kode konfirmasi.", en: "Failed to send the confirmation code.", ms: "Gagal menghantar kod pengesahan.", th: "ส่งรหัสยืนยันไม่สำเร็จ", fil: "Hindi naipadala ang confirmation code.", vi: "Không gửi được mã xác nhận." },
  "delAcc.confirmFailed": { id: "Gagal menghapus akun.", en: "Failed to delete the account.", ms: "Gagal memadam akaun.", th: "ลบบัญชีไม่สำเร็จ", fil: "Hindi nabura ang account.", vi: "Không xóa được tài khoản." },
});
