import { registerDict } from "./registry";

// Kontrol Lokal saat internet putus (NexbillAgent v1.4, lib/relay/local-control.ts) — halaman Kontrol Perangkat.
registerDict({
  "devices.local.title": { id: "Kontrol Lokal saat Internet Putus", en: "Local Control when the Internet Is Down", ms: "Kawalan Setempat semasa Internet Terputus", th: "การควบคุมภายในเมื่ออินเทอร์เน็ตหลุด", fil: "Local Control kapag Walang Internet", vi: "Điều khiển cục bộ khi mất internet" },
  "devices.local.desc": { id: "Selama router/WiFi outlet masih menyala, NexbillAgent tetap bisa menyalakan & mematikan Android TV dan smart plug Tasmota tanpa internet: otomatis dari Kasir Rental (Mode Offline), dan manual dari halaman Kontrol Lokal di HP/PC yang satu WiFi. Waktu sesi tetap dipantau agent — perangkat dimatikan saat waktunya habis.", en: "As long as the outlet router/WiFi is still on, NexbillAgent can turn Android TVs and Tasmota smart plugs on & off without internet: automatically from the Rental Cashier (Offline Mode), and manually from the Local Control page on any phone/PC on the same WiFi. The agent keeps tracking session time and turns devices off when time is up.", ms: "Selagi router/WiFi outlet masih hidup, NexbillAgent masih boleh menghidupkan & mematikan Android TV dan palam pintar Tasmota tanpa internet: secara automatik dari Juruwang Sewaan (Mod Luar Talian), dan secara manual dari halaman Kawalan Setempat pada telefon/PC dalam WiFi yang sama. Ejen terus memantau masa sesi dan mematikan peranti apabila masa tamat.", th: "ตราบใดที่เราเตอร์/WiFi ของร้านยังเปิดอยู่ NexbillAgent ยังเปิดและปิด Android TV และปลั๊กอัจฉริยะ Tasmota ได้โดยไม่ต้องใช้อินเทอร์เน็ต: อัตโนมัติจากแคชเชียร์เช่า (โหมดออฟไลน์) และด้วยตนเองจากหน้าการควบคุมภายในบนมือถือ/PC ที่ใช้ WiFi เดียวกัน เอเจนต์ยังจับเวลาเซสชันและปิดอุปกรณ์เมื่อหมดเวลา", fil: "Hangga't naka-on ang router/WiFi ng outlet, kaya pa rin ng NexbillAgent na i-on at i-off ang Android TV at Tasmota smart plug kahit walang internet: awtomatiko mula sa Rental Cashier (Offline Mode), at mano-mano mula sa Local Control page sa phone/PC na nasa parehong WiFi. Patuloy na binabantayan ng agent ang oras ng session at pinapatay ang device kapag ubos na ang oras.", vi: "Miễn là router/WiFi của cửa hàng còn bật, NexbillAgent vẫn bật và tắt được Android TV và ổ cắm thông minh Tasmota mà không cần internet: tự động từ Thu ngân cho thuê (Chế độ ngoại tuyến), và thủ công từ trang Điều khiển cục bộ trên điện thoại/PC dùng chung WiFi. Agent vẫn theo dõi thời gian phiên và tắt thiết bị khi hết giờ." },
  "devices.local.noAgent": { id: "Butuh NexbillAgent yang berjalan di PC atau HP Android outlet. Hubungi tim NEXBILL untuk aktivasi.", en: "Requires NexbillAgent running on the outlet's PC or Android phone. Contact the NEXBILL team for activation.", ms: "Memerlukan NexbillAgent yang berjalan pada PC atau telefon Android outlet. Hubungi pasukan NEXBILL untuk pengaktifan.", th: "ต้องมี NexbillAgent ทำงานบน PC หรือมือถือ Android ของร้าน ติดต่อทีม NEXBILL เพื่อเปิดใช้งาน", fil: "Kailangan ng NexbillAgent na tumatakbo sa PC o Android phone ng outlet. Makipag-ugnayan sa NEXBILL team para ma-activate.", vi: "Cần NexbillAgent chạy trên PC hoặc điện thoại Android của cửa hàng. Liên hệ đội NEXBILL để kích hoạt." },
  "devices.local.needsUpdate": { id: "Versi NexbillAgent ini belum punya Kontrol Lokal. Perbarui ke versi 1.4: di HP Android jalankan nexbill-update di Termux; di PC Windows unduh NexbillAgent terbaru lalu timpa file lama (token tetap tersimpan).", en: "This NexbillAgent version has no Local Control yet. Update to version 1.4: on an Android phone run nexbill-update in Termux; on a Windows PC download the latest NexbillAgent and replace the old files (the token stays saved).", ms: "Versi NexbillAgent ini belum mempunyai Kawalan Setempat. Kemas kini ke versi 1.4: pada telefon Android jalankan nexbill-update dalam Termux; pada PC Windows muat turun NexbillAgent terkini dan ganti fail lama (token kekal disimpan).", th: "NexbillAgent เวอร์ชันนี้ยังไม่มีการควบคุมภายใน อัปเดตเป็นเวอร์ชัน 1.4: บนมือถือ Android ให้รัน nexbill-update ใน Termux บน PC Windows ให้ดาวน์โหลด NexbillAgent ล่าสุดแล้วแทนที่ไฟล์เดิม (โทเค็นยังคงถูกบันทึกไว้)", fil: "Wala pang Local Control ang bersyong ito ng NexbillAgent. Mag-update sa bersyon 1.4: sa Android phone patakbuhin ang nexbill-update sa Termux; sa Windows PC i-download ang pinakabagong NexbillAgent at palitan ang lumang file (nananatiling naka-save ang token).", vi: "Phiên bản NexbillAgent này chưa có Điều khiển cục bộ. Cập nhật lên phiên bản 1.4: trên điện thoại Android chạy nexbill-update trong Termux; trên PC Windows tải NexbillAgent mới nhất rồi ghi đè tệp cũ (token vẫn được lưu)." },
  "devices.local.pageUrl": { id: "Halaman Kontrol Lokal (buka dari HP/PC di WiFi outlet)", en: "Local Control page (open from a phone/PC on the outlet WiFi)", ms: "Halaman Kawalan Setempat (buka dari telefon/PC pada WiFi outlet)", th: "หน้าการควบคุมภายใน (เปิดจากมือถือ/PC ที่ใช้ WiFi ของร้าน)", fil: "Local Control page (buksan mula sa phone/PC na nasa WiFi ng outlet)", vi: "Trang Điều khiển cục bộ (mở từ điện thoại/PC dùng WiFi của cửa hàng)" },
  "devices.local.urlUnknown": { id: "Alamat tampil di jendela NexbillAgent", en: "The address is shown in the NexbillAgent window", ms: "Alamat dipaparkan dalam tetingkap NexbillAgent", th: "ที่อยู่แสดงอยู่ในหน้าต่าง NexbillAgent", fil: "Makikita ang address sa window ng NexbillAgent", vi: "Địa chỉ hiển thị trong cửa sổ NexbillAgent" },
  "devices.local.pin": { id: "PIN Kontrol Lokal", en: "Local Control PIN", ms: "PIN Kawalan Setempat", th: "PIN การควบคุมภายใน", fil: "PIN ng Local Control", vi: "PIN điều khiển cục bộ" },
  "devices.local.covered": { id: "Bisa dikontrol saat offline:", en: "Controllable while offline:", ms: "Boleh dikawal semasa luar talian:", th: "ควบคุมได้ขณะออฟไลน์:", fil: "Makokontrol habang offline:", vi: "Điều khiển được khi ngoại tuyến:" },
  "devices.local.none": { id: "belum ada", en: "none yet", ms: "belum ada", th: "ยังไม่มี", fil: "wala pa", vi: "chưa có" },
  "devices.local.kind.plug": { id: "Smart plug", en: "Smart plug", ms: "Palam pintar", th: "ปลั๊กอัจฉริยะ", fil: "Smart plug", vi: "Ổ cắm thông minh" },
  "devices.local.kind.tv": { id: "Android TV", en: "Android TV", ms: "Android TV", th: "Android TV", fil: "Android TV", vi: "Android TV" },
  "devices.local.reason.noDevice": { id: "belum ada perangkat", en: "no device yet", ms: "belum ada peranti", th: "ยังไม่มีอุปกรณ์", fil: "wala pang device", vi: "chưa có thiết bị" },
  "devices.local.reason.cloudOnly": { id: "Tuya/eWeLink hanya bisa lewat internet", en: "Tuya/eWeLink only works over the internet", ms: "Tuya/eWeLink hanya berfungsi melalui internet", th: "Tuya/eWeLink ใช้งานได้ผ่านอินเทอร์เน็ตเท่านั้น", fil: "Gumagana lang ang Tuya/eWeLink sa internet", vi: "Tuya/eWeLink chỉ hoạt động qua internet" },
  "devices.local.reason.noLocalIp": { id: "IP lokal belum diisi", en: "local IP not set yet", ms: "IP setempat belum diisi", th: "ยังไม่ได้ตั้ง IP ภายใน", fil: "wala pang local IP", vi: "chưa nhập IP cục bộ" },
  "devices.local.reason.unsupported": { id: "jenis perangkat ini belum didukung", en: "this device type isn't supported yet", ms: "jenis peranti ini belum disokong", th: "ยังไม่รองรับอุปกรณ์ประเภทนี้", fil: "hindi pa suportado ang uri ng device na ito", vi: "loại thiết bị này chưa được hỗ trợ" },
  "devices.local.reason.otherAgent": { id: "dikontrol agent lain", en: "controlled by another agent", ms: "dikawal oleh ejen lain", th: "ควบคุมโดยเอเจนต์อื่น", fil: "kinokontrol ng ibang agent", vi: "do agent khác điều khiển" },
  "devices.local.detectFailed": { id: "IP smart plug tidak terdeteksi.", en: "The smart plug's IP could not be detected.", ms: "IP palam pintar tidak dapat dikesan.", th: "ตรวจไม่พบ IP ของปลั๊กอัจฉริยะ", fil: "Hindi ma-detect ang IP ng smart plug.", vi: "Không phát hiện được IP của ổ cắm thông minh." },
  "devices.local.detected": { id: "IP lokal smart plug terdeteksi: {ip}", en: "Smart plug local IP detected: {ip}", ms: "IP setempat palam pintar dikesan: {ip}", th: "ตรวจพบ IP ภายในของปลั๊กอัจฉริยะ: {ip}", fil: "Na-detect ang local IP ng smart plug: {ip}", vi: "Đã phát hiện IP cục bộ của ổ cắm thông minh: {ip}" },
  "devices.local.detecting": { id: "Mendeteksi...", en: "Detecting...", ms: "Mengesan...", th: "กำลังตรวจหา...", fil: "Dine-detect...", vi: "Đang dò..." },
  "devices.local.detect": { id: "Deteksi IP otomatis", en: "Detect IP automatically", ms: "Kesan IP secara automatik", th: "ตรวจหา IP อัตโนมัติ", fil: "I-detect ang IP nang awtomatiko", vi: "Tự động dò IP" },
  "devices.local.ipPlaceholder": { id: "IP lokal plug (opsional, mis. 192.168.1.23)", en: "Plug local IP (optional, e.g. 192.168.1.23)", ms: "IP setempat palam (pilihan, cth. 192.168.1.23)", th: "IP ภายในของปลั๊ก (ไม่บังคับ เช่น 192.168.1.23)", fil: "Local IP ng plug (opsyonal, hal. 192.168.1.23)", vi: "IP cục bộ của ổ cắm (tùy chọn, vd. 192.168.1.23)" },
  "devices.local.ipHint": { id: "IP lokal dipakai NexbillAgent untuk menyalakan/mematikan plug lewat WiFi saat internet putus. Kosongkan lalu pakai \"Deteksi IP otomatis\" di kartu Kontrol Lokal, dan atur IP tetap (DHCP reservation) untuk plug di router supaya tidak berubah.", en: "NexbillAgent uses the local IP to turn the plug on/off over WiFi when the internet is down. Leave it empty and use \"Detect IP automatically\" on the Local Control card, and give the plug a fixed IP (DHCP reservation) in the router so it doesn't change.", ms: "IP setempat digunakan NexbillAgent untuk menghidupkan/mematikan palam melalui WiFi apabila internet terputus. Biarkan kosong dan guna \"Kesan IP secara automatik\" pada kad Kawalan Setempat, dan tetapkan IP tetap (DHCP reservation) untuk palam dalam router supaya tidak berubah.", th: "NexbillAgent ใช้ IP ภายในเพื่อเปิด/ปิดปลั๊กผ่าน WiFi เมื่ออินเทอร์เน็ตหลุด เว้นว่างไว้แล้วใช้ \"ตรวจหา IP อัตโนมัติ\" ในการ์ดการควบคุมภายใน และตั้ง IP คงที่ (DHCP reservation) ให้ปลั๊กในเราเตอร์เพื่อไม่ให้เปลี่ยน", fil: "Ginagamit ng NexbillAgent ang local IP para i-on/i-off ang plug sa WiFi kapag walang internet. Iwanang blangko at gamitin ang \"I-detect ang IP nang awtomatiko\" sa Local Control card, at bigyan ang plug ng fixed IP (DHCP reservation) sa router para hindi ito magbago.", vi: "NexbillAgent dùng IP cục bộ để bật/tắt ổ cắm qua WiFi khi mất internet. Để trống rồi dùng \"Tự động dò IP\" trên thẻ Điều khiển cục bộ, và đặt IP cố định (DHCP reservation) cho ổ cắm trong router để IP không đổi." },
});
