import { registerDict } from "./registry";

/** Notifikasi push di HP (Pengaturan → Akun Saya) — lihat src/lib/push. */
registerDict({
  "push.heading": { id: "Notifikasi di HP", en: "Phone Notifications", ms: "Pemberitahuan di Telefon", th: "การแจ้งเตือนบนมือถือ", fil: "Mga Notification sa Phone", vi: "Thông báo trên điện thoại" },
  "push.desc": { id: "Terima notifikasi walau aplikasi ditutup: sesi hampir habis, permintaan QR pelanggan, booking, pembayaran QRIS, dan lainnya. Aktifkan di setiap HP/perangkat yang dipakai.", en: "Get notified even when the app is closed: sessions ending, customer QR requests, bookings, QRIS payments, and more. Turn it on on every phone/device you use.", ms: "Terima pemberitahuan walaupun aplikasi ditutup: sesi hampir tamat, permintaan QR pelanggan, tempahan, bayaran QRIS dan lain-lain. Aktifkan pada setiap telefon/peranti yang digunakan.", th: "รับการแจ้งเตือนแม้ปิดแอป: เซสชันใกล้หมด คำขอจาก QR ลูกค้า การจอง การชำระ QRIS และอื่นๆ เปิดใช้ในทุกมือถือ/อุปกรณ์ที่ใช้", fil: "Makatanggap ng notification kahit sarado ang app: patapos na session, customer QR request, booking, QRIS payment, at iba pa. I-on sa bawat phone/device na gamit.", vi: "Nhận thông báo ngay cả khi đóng ứng dụng: phiên sắp hết, yêu cầu QR của khách, đặt chỗ, thanh toán QRIS và hơn nữa. Bật trên mọi điện thoại/thiết bị đang dùng." },
  "push.unsupported": { id: "Perangkat atau browser ini tidak mendukung notifikasi push. Pakai aplikasi NEXBILL Android atau Chrome di Android/PC.", en: "This device or browser doesn't support push notifications. Use the NEXBILL Android app or Chrome on Android/PC.", ms: "Peranti atau pelayar ini tidak menyokong pemberitahuan push. Gunakan aplikasi NEXBILL Android atau Chrome di Android/PC.", th: "อุปกรณ์หรือเบราว์เซอร์นี้ไม่รองรับการแจ้งเตือนแบบพุช ใช้แอป NEXBILL Android หรือ Chrome บน Android/PC", fil: "Hindi suportado ng device o browser na ito ang push notifications. Gamitin ang NEXBILL Android app o Chrome sa Android/PC.", vi: "Thiết bị hoặc trình duyệt này không hỗ trợ thông báo đẩy. Dùng ứng dụng NEXBILL Android hoặc Chrome trên Android/PC." },
  "push.notConfigured": { id: "Notifikasi push belum diaktifkan di server NEXBILL.", en: "Push notifications aren't enabled on the NEXBILL server yet.", ms: "Pemberitahuan push belum diaktifkan di pelayan NEXBILL.", th: "ยังไม่ได้เปิดการแจ้งเตือนแบบพุชบนเซิร์ฟเวอร์ NEXBILL", fil: "Hindi pa naka-enable ang push notifications sa NEXBILL server.", vi: "Máy chủ NEXBILL chưa bật thông báo đẩy." },
  "push.denied": { id: "Izin notifikasi ditolak. Buka pengaturan aplikasi/browser → Notifikasi → izinkan untuk NEXBILL, lalu coba lagi.", en: "Notification permission was denied. Open the app/browser settings → Notifications → allow NEXBILL, then try again.", ms: "Kebenaran pemberitahuan ditolak. Buka tetapan aplikasi/pelayar → Pemberitahuan → benarkan NEXBILL, kemudian cuba lagi.", th: "ถูกปฏิเสธสิทธิ์การแจ้งเตือน เปิดการตั้งค่าแอป/เบราว์เซอร์ → การแจ้งเตือน → อนุญาต NEXBILL แล้วลองอีกครั้ง", fil: "Tinanggihan ang pahintulot sa notification. Buksan ang settings ng app/browser → Notifications → payagan ang NEXBILL, saka subukan muli.", vi: "Quyền thông báo bị từ chối. Mở cài đặt ứng dụng/trình duyệt → Thông báo → cho phép NEXBILL rồi thử lại." },
  "push.enable": { id: "Aktifkan Notifikasi di Perangkat Ini", en: "Turn On Notifications on This Device", ms: "Aktifkan Pemberitahuan pada Peranti Ini", th: "เปิดการแจ้งเตือนบนอุปกรณ์นี้", fil: "I-on ang Notifications sa Device na Ito", vi: "Bật thông báo trên thiết bị này" },
  "push.disable": { id: "Matikan di Perangkat Ini", en: "Turn Off on This Device", ms: "Matikan pada Peranti Ini", th: "ปิดบนอุปกรณ์นี้", fil: "I-off sa Device na Ito", vi: "Tắt trên thiết bị này" },
  "push.enabledHere": { id: "Aktif di perangkat ini", en: "On for this device", ms: "Aktif pada peranti ini", th: "เปิดอยู่บนอุปกรณ์นี้", fil: "Naka-on sa device na ito", vi: "Đang bật trên thiết bị này" },
  "push.devices": { id: "{n} perangkat terdaftar untuk akun ini", en: "{n} devices registered to this account", ms: "{n} peranti didaftarkan untuk akaun ini", th: "ลงทะเบียน {n} อุปกรณ์สำหรับบัญชีนี้", fil: "{n} device ang naka-register sa account na ito", vi: "{n} thiết bị đã đăng ký cho tài khoản này" },
  "push.test": { id: "Kirim Notifikasi Uji", en: "Send Test Notification", ms: "Hantar Pemberitahuan Ujian", th: "ส่งการแจ้งเตือนทดสอบ", fil: "Magpadala ng Test Notification", vi: "Gửi thông báo thử" },
  "push.testSent": { id: "Notifikasi uji dikirim ke {n} perangkat.", en: "Test notification sent to {n} devices.", ms: "Pemberitahuan ujian dihantar ke {n} peranti.", th: "ส่งการแจ้งเตือนทดสอบไปยัง {n} อุปกรณ์แล้ว", fil: "Naipadala ang test notification sa {n} device.", vi: "Đã gửi thông báo thử tới {n} thiết bị." },
  "push.categories": { id: "Jenis notifikasi untuk akun ini", en: "Notification types for this account", ms: "Jenis pemberitahuan untuk akaun ini", th: "ประเภทการแจ้งเตือนของบัญชีนี้", fil: "Mga uri ng notification para sa account na ito", vi: "Loại thông báo cho tài khoản này" },
  "push.cat.session": { id: "Sesi bilik hampir habis / sudah habis", en: "Booth session ending / ended", ms: "Sesi bilik hampir tamat / sudah tamat", th: "เซสชันบูธใกล้หมด / หมดแล้ว", fil: "Patapos na / tapos na ang session sa booth", vi: "Phiên phòng sắp hết / đã hết" },
  "push.cat.customer_request": { id: "Permintaan QR pelanggan (pesan F&B, tambah waktu, panggil kasir)", en: "Customer QR requests (F&B order, add time, call cashier)", ms: "Permintaan QR pelanggan (pesanan F&B, tambah masa, panggil juruwang)", th: "คำขอจาก QR ลูกค้า (สั่งอาหาร เพิ่มเวลา เรียกแคชเชียร์)", fil: "Customer QR request (F&B order, dagdag oras, tawag sa cashier)", vi: "Yêu cầu QR của khách (gọi món, thêm giờ, gọi thu ngân)" },
  "push.cat.booking": { id: "Booking online masuk", en: "New online bookings", ms: "Tempahan dalam talian baharu", th: "การจองออนไลน์ใหม่", fil: "Bagong online booking", vi: "Đặt chỗ online mới" },
  "push.cat.payment": { id: "Pembayaran QRIS/online diterima", en: "QRIS/online payments received", ms: "Bayaran QRIS/dalam talian diterima", th: "ได้รับชำระเงิน QRIS/ออนไลน์", fil: "Natanggap na QRIS/online payment", vi: "Đã nhận thanh toán QRIS/online" },
  "push.cat.fraud": { id: "Shift ditandai berisiko (anti-fraud)", en: "Shift flagged as risky (anti-fraud)", ms: "Syif ditanda berisiko (anti-penipuan)", th: "กะถูกทำเครื่องหมายว่าเสี่ยง (ป้องกันทุจริต)", fil: "Shift na may risk flag (anti-fraud)", vi: "Ca bị gắn cờ rủi ro (chống gian lận)" },
  "push.cat.low_stock": { id: "Stok menipis", en: "Low stock", ms: "Stok rendah", th: "สต็อกใกล้หมด", fil: "Paubos na stock", vi: "Sắp hết hàng" },
  "push.cat.shift_summary": { id: "Ringkasan omzet saat tutup shift", en: "Revenue summary when a shift closes", ms: "Ringkasan hasil semasa syif ditutup", th: "สรุปยอดขายเมื่อปิดกะ", fil: "Buod ng kita kapag isinara ang shift", vi: "Tóm tắt doanh thu khi đóng ca" },
});
