import { registerDict } from "./registry";

/** Scan kamera (barcode produk di Kasir, QR kartu member di Rental PS) — lihat components/scanner. */
registerDict({
  "scanner.title": { id: "Scan dengan Kamera", en: "Scan with Camera", ms: "Imbas dengan Kamera", th: "สแกนด้วยกล้อง", fil: "I-scan gamit ang Camera", vi: "Quét bằng camera" },
  "scanner.button": { id: "Scan kamera", en: "Camera scan", ms: "Imbas kamera", th: "สแกนกล้อง", fil: "Camera scan", vi: "Quét camera" },
  "scanner.hintProduct": { id: "Arahkan kamera ke barcode produk. Bisa scan beberapa produk berturut-turut.", en: "Point the camera at a product barcode. You can scan several products in a row.", ms: "Halakan kamera ke kod bar produk. Boleh imbas beberapa produk berturut-turut.", th: "เล็งกล้องไปที่บาร์โค้ดสินค้า สแกนหลายชิ้นต่อกันได้", fil: "Itutok ang camera sa barcode ng produkto. Puwedeng mag-scan ng ilang produkto nang sunod-sunod.", vi: "Hướng camera vào mã vạch sản phẩm. Có thể quét nhiều sản phẩm liên tiếp." },
  "scanner.hintMember": { id: "Arahkan kamera ke QR atau barcode kartu member.", en: "Point the camera at the member card's QR or barcode.", ms: "Halakan kamera ke QR atau kod bar kad ahli.", th: "เล็งกล้องไปที่ QR หรือบาร์โค้ดบัตรสมาชิก", fil: "Itutok ang camera sa QR o barcode ng member card.", vi: "Hướng camera vào QR hoặc mã vạch thẻ thành viên." },
  "scanner.starting": { id: "Membuka kamera...", en: "Opening camera...", ms: "Membuka kamera...", th: "กำลังเปิดกล้อง...", fil: "Binubuksan ang camera...", vi: "Đang mở camera..." },
  "scanner.denied": { id: "Izin kamera ditolak. Izinkan kamera untuk NEXBILL di pengaturan browser/aplikasi, lalu coba lagi.", en: "Camera permission denied. Allow the camera for NEXBILL in browser/app settings, then try again.", ms: "Kebenaran kamera ditolak. Benarkan kamera untuk NEXBILL dalam tetapan pelayar/aplikasi, kemudian cuba lagi.", th: "ถูกปฏิเสธสิทธิ์กล้อง อนุญาตกล้องให้ NEXBILL ในการตั้งค่าเบราว์เซอร์/แอป แล้วลองอีกครั้ง", fil: "Tinanggihan ang camera permission. Payagan ang camera para sa NEXBILL sa settings ng browser/app, saka subukan muli.", vi: "Quyền camera bị từ chối. Cho phép camera cho NEXBILL trong cài đặt trình duyệt/ứng dụng rồi thử lại." },
  "scanner.noCamera": { id: "Kamera tidak tersedia di perangkat ini.", en: "No camera is available on this device.", ms: "Kamera tidak tersedia pada peranti ini.", th: "ไม่มีกล้องในอุปกรณ์นี้", fil: "Walang camera sa device na ito.", vi: "Thiết bị này không có camera." },
  "scanner.close": { id: "Selesai", en: "Done", ms: "Selesai", th: "เสร็จสิ้น", fil: "Tapos na", vi: "Xong" },
  "scanner.switch": { id: "Ganti kamera", en: "Switch camera", ms: "Tukar kamera", th: "สลับกล้อง", fil: "Palitan ang camera", vi: "Đổi camera" },
  "scanner.added": { id: "Ditambahkan: {name}", en: "Added: {name}", ms: "Ditambah: {name}", th: "เพิ่มแล้ว: {name}", fil: "Naidagdag: {name}", vi: "Đã thêm: {name}" },
  "scanner.notFound": { id: "Kode {code} tidak ditemukan di produk.", en: "Code {code} doesn't match any product.", ms: "Kod {code} tiada dalam produk.", th: "ไม่พบรหัส {code} ในสินค้า", fil: "Walang produktong may code na {code}.", vi: "Không tìm thấy sản phẩm có mã {code}." },
  "scanner.memberNotFound": { id: "Member dengan kode {code} tidak ditemukan.", en: "No member found with code {code}.", ms: "Ahli dengan kod {code} tidak ditemui.", th: "ไม่พบสมาชิกรหัส {code}", fil: "Walang member na may code na {code}.", vi: "Không tìm thấy thành viên có mã {code}." },
  "member.qrTitle": { id: "QR Kartu Member", en: "Member Card QR", ms: "QR Kad Ahli", th: "QR บัตรสมาชิก", fil: "QR ng Member Card", vi: "QR thẻ thành viên" },
  "member.qrHint": { id: "Cetak atau kirim ke pelanggan — kasir cukup scan QR ini di Rental PS.", en: "Print it or send it to the customer — the cashier just scans this QR in Rental PS.", ms: "Cetak atau hantar kepada pelanggan — juruwang hanya perlu imbas QR ini di Rental PS.", th: "พิมพ์หรือส่งให้ลูกค้า — แคชเชียร์แค่สแกน QR นี้ในหน้า Rental PS", fil: "I-print o ipadala sa customer — i-scan lang ng cashier ang QR na ito sa Rental PS.", vi: "In hoặc gửi cho khách — thu ngân chỉ cần quét QR này trong Rental PS." },
  "member.qrDownload": { id: "Unduh QR", en: "Download QR", ms: "Muat turun QR", th: "ดาวน์โหลด QR", fil: "I-download ang QR", vi: "Tải QR" },
});
