import { registerDict } from "./registry";

/**
 * Translations for /dashboard/maintenance — the asset repair/maintenance ticket workflow
 * (queued → in_progress → done). Registered as a side effect on import; import this file once
 * near the top of the maintenance page before any component calls useDashboardLang().t().
 */
registerDict({
  // --- Asset categories (shared with the ticket table + "new ticket" asset picker) ---
  "maintenance.category.playstation": { id: "PlayStation / Konsol", en: "PlayStation / Console", ms: "PlayStation / Konsol", th: "เพลย์สเตชัน / คอนโซล", fil: "PlayStation / Console", vi: "PlayStation / Máy chơi game" },
  "maintenance.category.tv": { id: "TV", en: "TV", ms: "TV", th: "ทีวี", fil: "TV", vi: "TV" },
  "maintenance.category.controller": { id: "Controller / Aksesoris", en: "Controller / Accessories", ms: "Kawalan / Aksesori", th: "จอยควบคุม / อุปกรณ์เสริม", fil: "Controller / Accessories", vi: "Tay cầm / Phụ kiện" },
  "maintenance.category.furniture": { id: "Furniture", en: "Furniture", ms: "Perabot", th: "เฟอร์นิเจอร์", fil: "Kasangkapan", vi: "Nội thất" },
  "maintenance.category.vehicle": { id: "Kendaraan", en: "Vehicle", ms: "Kenderaan", th: "ยานพาหนะ", fil: "Sasakyan", vi: "Phương tiện" },
  "maintenance.category.other": { id: "Lainnya", en: "Other", ms: "Lain-lain", th: "อื่นๆ", fil: "Iba pa", vi: "Khác" },

  // --- Ticket status ---
  "maintenance.status.queued": { id: "Masuk Maintenance", en: "Queued for Repair", ms: "Masuk Penyelenggaraan", th: "รอซ่อมบำรุง", fil: "Pasok sa Maintenance", vi: "Chờ bảo trì" },
  "maintenance.status.inProgress": { id: "Proses", en: "In Progress", ms: "Dalam Proses", th: "กำลังดำเนินการ", fil: "Isinasagawa", vi: "Đang xử lý" },
  "maintenance.status.done": { id: "Selesai", en: "Done", ms: "Selesai", th: "เสร็จสิ้น", fil: "Tapos na", vi: "Hoàn tất" },
  "maintenance.filterAll": { id: "Semua", en: "All", ms: "Semua", th: "ทั้งหมด", fil: "Lahat", vi: "Tất cả" },

  // --- Header ---
  "maintenance.title": { id: "Maintenance / Perbaikan", en: "Maintenance / Repairs", ms: "Penyelenggaraan / Pembaikan", th: "ซ่อมบำรุง / ซ่อมแซม", fil: "Maintenance / Pagkukumpuni", vi: "Bảo trì / Sửa chữa" },
  "maintenance.subtitlePrefix": { id: "Alur perbaikan TV, konsol, controller & aksesoris lain: Masuk Maintenance → Proses → Selesai. Data aset diambil langsung dari halaman", en: "Repair flow for TVs, consoles, controllers & other accessories: Queued for Repair → In Progress → Done. Asset data is pulled directly from the", ms: "Aliran pembaikan TV, konsol, kawalan & aksesori lain: Masuk Penyelenggaraan → Dalam Proses → Selesai. Data aset diambil terus daripada halaman", th: "ขั้นตอนการซ่อมทีวี คอนโซล จอยควบคุม และอุปกรณ์เสริมอื่นๆ: รอซ่อมบำรุง → กำลังดำเนินการ → เสร็จสิ้น ข้อมูลสินทรัพย์ดึงมาจากหน้า", fil: "Daloy ng pagkukumpuni ng TV, console, controller at iba pang accessories: Pasok sa Maintenance → Isinasagawa → Tapos na. Direktang kinukuha ang data ng asset mula sa pahina ng", vi: "Quy trình sửa chữa TV, máy chơi game, tay cầm & phụ kiện khác: Chờ bảo trì → Đang xử lý → Hoàn tất. Dữ liệu tài sản được lấy trực tiếp từ trang" },
  "maintenance.assetsLinkText": { id: "Aset", en: "Assets", ms: "Aset", th: "สินทรัพย์", fil: "Assets", vi: "Tài sản" },

  // --- Category summary cards ---
  "maintenance.availableOfTotal": { id: "tersedia / {total} total", en: "available / {total} total", ms: "tersedia / {total} jumlah", th: "พร้อมใช้งาน / รวม {total}", fil: "available / {total} kabuuan", vi: "còn dùng được / {total} tổng" },
  "maintenance.underMaintenanceCount": { id: "{n} sedang maintenance", en: "{n} under maintenance", ms: "{n} sedang diselenggara", th: "{n} เครื่องกำลังซ่อมบำรุง", fil: "{n} na nasa maintenance", vi: "{n} đang bảo trì" },
  "maintenance.noAssetsRegistered": { id: "Belum ada aset terdaftar — tambahkan dulu di halaman Aset.", en: "No assets registered yet — add one on the Assets page first.", ms: "Belum ada aset didaftarkan — tambah dahulu di halaman Aset.", th: "ยังไม่มีสินทรัพย์ที่ลงทะเบียน — โปรดเพิ่มที่หน้าสินทรัพย์ก่อน", fil: "Wala pang nakarehistrong asset — magdagdag muna sa pahina ng Assets.", vi: "Chưa có tài sản nào được đăng ký — hãy thêm tại trang Tài sản trước." },

  // --- Toolbar / toggle ---
  "maintenance.closeForm": { id: "Tutup Form", en: "Close Form", ms: "Tutup Borang", th: "ปิดแบบฟอร์ม", fil: "Isara ang Form", vi: "Đóng biểu mẫu" },
  "maintenance.addMaintenance": { id: "+ Tambah Maintenance", en: "+ Add Maintenance", ms: "+ Tambah Penyelenggaraan", th: "+ เพิ่มงานซ่อมบำรุง", fil: "+ Magdagdag ng Maintenance", vi: "+ Thêm bảo trì" },

  // --- New ticket form ---
  "maintenance.newTicketHeading": { id: "Tiket Maintenance Baru", en: "New Maintenance Ticket", ms: "Tiket Penyelenggaraan Baharu", th: "ตั๋วซ่อมบำรุงใหม่", fil: "Bagong Maintenance Ticket", vi: "Phiếu bảo trì mới" },
  "maintenance.selectAssetPlaceholder": { id: "Pilih aset...", en: "Select an asset...", ms: "Pilih aset...", th: "เลือกสินทรัพย์...", fil: "Pumili ng asset...", vi: "Chọn tài sản..." },
  "maintenance.ticketAlreadyRunning": { id: " (sudah ada tiket berjalan)", en: " (a ticket is already in progress)", ms: " (sudah ada tiket berjalan)", th: " (มีตั๋วที่กำลังดำเนินการอยู่แล้ว)", fil: " (may tiket na na patakbo)", vi: " (đã có phiếu đang xử lý)" },
  // Deep link from Rental's "Set Maintenance" button when the unit has no linked Fixed Asset yet.
  "maintenance.deepLinkNoAsset": {
    id: "Unit ini belum terhubung ke Aset manapun, jadi belum bisa dipilih otomatis. Pilih asetnya manual di bawah, atau hubungkan unit ini ke sebuah Aset dulu di halaman Aset.",
    en: "This unit isn't linked to any Asset yet, so it couldn't be auto-selected. Pick the asset manually below, or link this unit to an Asset first on the Assets page.",
    ms: "Unit ini belum disambungkan ke mana-mana Aset, jadi tidak dapat dipilih secara automatik. Pilih aset secara manual di bawah, atau sambungkan unit ini ke satu Aset dahulu di halaman Aset.",
    th: "ยูนิตนี้ยังไม่ได้เชื่อมกับสินทรัพย์ใดๆ จึงเลือกให้อัตโนมัติไม่ได้ กรุณาเลือกสินทรัพย์เองด้านล่าง หรือเชื่อมยูนิตนี้กับสินทรัพย์ที่หน้าสินทรัพย์ก่อน",
    fil: "Ang unit na ito ay hindi pa naka-link sa anumang Asset, kaya hindi ito awtomatikong napili. Piliin ang asset nang manu-mano sa ibaba, o i-link muna ang unit na ito sa isang Asset sa pahina ng Assets.",
    vi: "Unit này chưa được liên kết với Tài sản nào, nên không thể tự động chọn. Hãy chọn tài sản thủ công bên dưới, hoặc liên kết unit này với một Tài sản trước tại trang Tài sản.",
  },
  "maintenance.costPlaceholder": { id: "Biaya (Rp, 0 jika belum tahu)", en: "Cost (Rp, 0 if unknown)", ms: "Kos (Rp, 0 jika belum diketahui)", th: "ค่าใช้จ่าย (Rp, 0 หากยังไม่ทราบ)", fil: "Gastos (Rp, 0 kung hindi pa alam)", vi: "Chi phí (Rp, để 0 nếu chưa biết)" },
  "maintenance.descriptionPlaceholder": { id: "Deskripsi kerusakan (mis. Layar TV bergaris)", en: "Damage description (e.g. TV screen has lines)", ms: "Penerangan kerosakan (cth. Skrin TV bergaris)", th: "รายละเอียดความเสียหาย (เช่น จอทีวีมีเส้น)", fil: "Deskripsyon ng sira (hal. May guhit ang screen ng TV)", vi: "Mô tả hư hỏng (vd: Màn hình TV bị sọc)" },
  "maintenance.createExpenseCheckbox": { id: "Buat Expense (Beban Maintenance) sekarang", en: "Create an expense (maintenance cost) now", ms: "Buat Perbelanjaan (Kos Penyelenggaraan) sekarang", th: "สร้างรายจ่าย (ค่าซ่อมบำรุง) ตอนนี้", fil: "Gumawa ng Expense (Gastos sa Maintenance) ngayon", vi: "Tạo chi phí (bảo trì) ngay" },
  "maintenance.expenseAccountPlaceholder": { id: "Akun Beban (COA)", en: "Expense Account (COA)", ms: "Akaun Perbelanjaan (COA)", th: "บัญชีค่าใช้จ่าย (COA)", fil: "Expense Account (COA)", vi: "Tài khoản chi phí (COA)" },
  "maintenance.cashBankAccountPlaceholder": { id: "Akun Kas/Bank (kosongkan = hutang)", en: "Cash/Bank Account (leave blank = payable)", ms: "Akaun Tunai/Bank (kosongkan = hutang)", th: "บัญชีเงินสด/ธนาคาร (เว้นว่าง = เจ้าหนี้)", fil: "Cash/Bank Account (iwanang blangko = utang)", vi: "Tài khoản tiền mặt/ngân hàng (để trống = công nợ)" },
  "maintenance.saveTicket": { id: "Simpan Tiket", en: "Save Ticket", ms: "Simpan Tiket", th: "บันทึกตั๋ว", fil: "I-save ang Ticket", vi: "Lưu phiếu" },

  // --- Ticket table ---
  "maintenance.col.asset": { id: "Aset", en: "Asset", ms: "Aset", th: "สินทรัพย์", fil: "Asset", vi: "Tài sản" },
  "maintenance.col.category": { id: "Kategori", en: "Category", ms: "Kategori", th: "หมวดหมู่", fil: "Kategorya", vi: "Danh mục" },
  "maintenance.col.description": { id: "Deskripsi", en: "Description", ms: "Penerangan", th: "รายละเอียด", fil: "Deskripsyon", vi: "Mô tả" },
  "maintenance.col.cost": { id: "Biaya", en: "Cost", ms: "Kos", th: "ค่าใช้จ่าย", fil: "Gastos", vi: "Chi phí" },
  "maintenance.col.status": { id: "Status", en: "Status", ms: "Status", th: "สถานะ", fil: "Status", vi: "Trạng thái" },
  "maintenance.col.dateIn": { id: "Masuk", en: "Date In", ms: "Tarikh Masuk", th: "วันที่รับเข้า", fil: "Petsa Pasok", vi: "Ngày vào" },
  "maintenance.deletedAsset": { id: "(aset terhapus)", en: "(deleted asset)", ms: "(aset dipadam)", th: "(สินทรัพย์ที่ถูกลบ)", fil: "(tinanggal na asset)", vi: "(tài sản đã xóa)" },
  "maintenance.recordedAsExpenseTitle": { id: "Sudah tercatat sebagai Expense — ubah lewat halaman Expense.", en: "Already recorded as an expense — edit it from the Expenses page.", ms: "Sudah direkodkan sebagai Perbelanjaan — ubah melalui halaman Perbelanjaan.", th: "บันทึกเป็นรายจ่ายแล้ว — แก้ไขได้ที่หน้ารายจ่าย", fil: "Naitala na bilang Expense — i-edit sa pahina ng Expense.", vi: "Đã được ghi nhận là chi phí — chỉnh sửa tại trang Chi phí." },

  // --- Row actions ---
  "maintenance.save": { id: "Simpan", en: "Save", ms: "Simpan", th: "บันทึก", fil: "I-save", vi: "Lưu" },
  "maintenance.cancel": { id: "Batal", en: "Cancel", ms: "Batal", th: "ยกเลิก", fil: "Kanselahin", vi: "Hủy" },
  "maintenance.startProcess": { id: "Mulai Proses", en: "Start Processing", ms: "Mula Proses", th: "เริ่มดำเนินการ", fil: "Simulan ang Proseso", vi: "Bắt đầu xử lý" },
  "maintenance.markDone": { id: "Tandai Selesai", en: "Mark as Done", ms: "Tanda Selesai", th: "ทำเครื่องหมายว่าเสร็จสิ้น", fil: "Markahan bilang Tapos na", vi: "Đánh dấu hoàn tất" },
  "maintenance.edit": { id: "Edit", en: "Edit", ms: "Edit", th: "แก้ไข", fil: "I-edit", vi: "Sửa" },
  "maintenance.delete": { id: "Hapus", en: "Delete", ms: "Padam", th: "ลบ", fil: "Tanggalin", vi: "Xóa" },
  "maintenance.noTickets": { id: "Belum ada tiket maintenance.", en: "No maintenance tickets yet.", ms: "Belum ada tiket penyelenggaraan.", th: "ยังไม่มีตั๋วซ่อมบำรุง", fil: "Wala pang maintenance ticket.", vi: "Chưa có phiếu bảo trì nào." },

  // --- Alerts / confirms ---
  "maintenance.alertSelectAsset": { id: "Pilih aset yang mau di-maintenance.", en: "Select the asset to send for maintenance.", ms: "Pilih aset yang hendak diselenggara.", th: "โปรดเลือกสินทรัพย์ที่ต้องการซ่อมบำรุง", fil: "Pumili ng asset na gustong i-maintenance.", vi: "Chọn tài sản cần bảo trì." },
  "maintenance.alertDescriptionRequired": { id: "Deskripsi maintenance wajib diisi.", en: "A maintenance description is required.", ms: "Penerangan penyelenggaraan wajib diisi.", th: "กรุณากรอกรายละเอียดการซ่อมบำรุง", fil: "Kinakailangan ang deskripsyon ng maintenance.", vi: "Vui lòng nhập mô tả bảo trì." },
  "maintenance.alertSelectExpenseAccount": { id: "Pilih akun beban untuk membuat expense maintenance.", en: "Select an expense account to create the maintenance expense.", ms: "Pilih akaun perbelanjaan untuk membuat perbelanjaan penyelenggaraan.", th: "โปรดเลือกบัญชีค่าใช้จ่ายเพื่อสร้างรายจ่ายซ่อมบำรุง", fil: "Pumili ng expense account para gumawa ng maintenance expense.", vi: "Chọn tài khoản chi phí để tạo chi phí bảo trì." },
  "maintenance.confirmDeleteTicket": { id: 'Hapus tiket maintenance "{desc}"? Tindakan ini permanen.', en: 'Delete the maintenance ticket "{desc}"? This action is permanent.', ms: 'Padam tiket penyelenggaraan "{desc}"? Tindakan ini kekal.', th: 'ลบตั๋วซ่อมบำรุง "{desc}" หรือไม่? การกระทำนี้ถาวร', fil: 'Tatanggalin ang maintenance ticket na "{desc}"? Permanente ang aksyon na ito.', vi: 'Xóa phiếu bảo trì "{desc}"? Hành động này không thể hoàn tác.' },

  // --- Damage classification (new ticket form, edit mode, table column) ---
  "maintenance.col.damage": { id: "Kerusakan", en: "Damage", ms: "Kerosakan", th: "ความเสียหาย", fil: "Sira", vi: "Hư hỏng" },
  "maintenance.damageLabelPlaceholder": { id: "Label kerusakan (mis. Stik drift)", en: "Damage label (e.g. Stick drift)", ms: "Label kerosakan (cth. Stick drift)", th: "ป้ายความเสียหาย (เช่น จอยดริฟท์)", fil: "Label ng sira (hal. Stick drift)", vi: "Nhãn hư hỏng (vd: Cần analog bị lệch)" },
  "maintenance.damageTypePlaceholder": { id: "Jenis kerusakan...", en: "Damage type...", ms: "Jenis kerosakan...", th: "ประเภทความเสียหาย...", fil: "Uri ng sira...", vi: "Loại hư hỏng..." },
  "maintenance.damageSeverityPlaceholder": { id: "Kategori kerusakan...", en: "Damage category...", ms: "Kategori kerosakan...", th: "หมวดหมู่ความเสียหาย...", fil: "Kategorya ng sira...", vi: "Mức độ hư hỏng..." },
  "maintenance.damageType.fisik": { id: "Fisik", en: "Physical", ms: "Fizikal", th: "ทางกายภาพ", fil: "Pisikal", vi: "Vật lý" },
  "maintenance.damageType.elektronik": { id: "Elektronik", en: "Electronic", ms: "Elektronik", th: "อิเล็กทรอนิกส์", fil: "Elektroniko", vi: "Điện tử" },
  "maintenance.damageType.konektorPort": { id: "Konektor / Port", en: "Connector / Port", ms: "Penyambung / Port", th: "ขั้วต่อ / พอร์ต", fil: "Connector / Port", vi: "Cổng kết nối" },
  "maintenance.damageType.softwareFirmware": { id: "Software / Firmware", en: "Software / Firmware", ms: "Perisian / Firmware", th: "ซอฟต์แวร์ / เฟิร์มแวร์", fil: "Software / Firmware", vi: "Phần mềm / Firmware" },
  "maintenance.damageType.bateraiPower": { id: "Baterai / Power", en: "Battery / Power", ms: "Bateri / Kuasa", th: "แบตเตอรี่ / ไฟเลี้ยง", fil: "Baterya / Power", vi: "Pin / Nguồn điện" },
  "maintenance.damageType.lainnya": { id: "Lainnya", en: "Other", ms: "Lain-lain", th: "อื่นๆ", fil: "Iba pa", vi: "Khác" },
  "maintenance.damageSeverity.ringan": { id: "Rusak Ringan", en: "Minor Damage", ms: "Kerosakan Ringan", th: "เสียหายเล็กน้อย", fil: "Bahagyang Sira", vi: "Hư hỏng nhẹ" },
  "maintenance.damageSeverity.berat": { id: "Rusak Berat", en: "Severe Damage", ms: "Kerosakan Teruk", th: "เสียหายหนัก", fil: "Malubhang Sira", vi: "Hư hỏng nặng" },
  "maintenance.damageSeverity.unrepairable": { id: "Tidak Bisa Diperbaiki", en: "Unrepairable", ms: "Tidak Boleh Dibaiki", th: "ไม่สามารถซ่อมได้", fil: "Hindi Na Maaayos", vi: "Không thể sửa chữa" },

  // --- Spare parts panel (per-ticket, expandable) ---
  "maintenance.parts.toggle": { id: "Sparepart", en: "Parts", ms: "Alat Ganti", th: "อะไหล่", fil: "Spare Parts", vi: "Linh kiện" },
  "maintenance.parts.heading": { id: "Sparepart Dipakai", en: "Parts Used", ms: "Alat Ganti Digunakan", th: "อะไหล่ที่ใช้", fil: "Ginamit na Spare Parts", vi: "Linh kiện đã dùng" },
  "maintenance.parts.empty": { id: "Belum ada sparepart dipakai untuk tiket ini.", en: "No parts used for this ticket yet.", ms: "Belum ada alat ganti digunakan untuk tiket ini.", th: "ยังไม่มีอะไหล่ที่ใช้สำหรับตั๋วนี้", fil: "Wala pang spare parts na ginamit para sa ticket na ito.", vi: "Chưa có linh kiện nào được dùng cho phiếu này." },
  "maintenance.parts.deletedProduct": { id: "(sparepart terhapus)", en: "(deleted part)", ms: "(alat ganti dipadam)", th: "(อะไหล่ที่ถูกลบ)", fil: "(tinanggal na parte)", vi: "(linh kiện đã xóa)" },
  "maintenance.parts.total": { id: "Total Biaya Sparepart", en: "Total Parts Cost", ms: "Jumlah Kos Alat Ganti", th: "รวมค่าอะไหล่", fil: "Kabuuang Gastos sa Parts", vi: "Tổng chi phí linh kiện" },
  "maintenance.parts.noSpareParts": { id: "Belum ada sparepart terdaftar — tambahkan dulu di halaman", en: "No parts registered yet — add one first on the", ms: "Belum ada alat ganti didaftarkan — tambah dahulu di halaman", th: "ยังไม่มีอะไหล่ที่ลงทะเบียน — โปรดเพิ่มที่หน้า", fil: "Wala pang nakarehistrong spare part — magdagdag muna sa pahina ng", vi: "Chưa có linh kiện nào được đăng ký — hãy thêm tại trang" },
  "maintenance.parts.inventoryLinkText": { id: "Inventory Control", en: "Inventory Control", ms: "Inventory Control", th: "Inventory Control", fil: "Inventory Control", vi: "Inventory Control" },
  "maintenance.parts.categoryHint": { id: "kategori Sparepart & Komponen", en: "Sparepart & Component category", ms: "kategori Alat Ganti & Komponen", th: "หมวดหมู่อะไหล่และชิ้นส่วน", fil: "kategoryang Sparepart & Component", vi: "danh mục Linh kiện & Phụ tùng" },
  "maintenance.parts.selectPlaceholder": { id: "Pilih sparepart...", en: "Select a part...", ms: "Pilih alat ganti...", th: "เลือกอะไหล่...", fil: "Pumili ng spare part...", vi: "Chọn linh kiện..." },
  "maintenance.parts.qtyPlaceholder": { id: "Qty", en: "Qty", ms: "Kuantiti", th: "จำนวน", fil: "Qty", vi: "SL" },
  "maintenance.parts.add": { id: "+ Tambah", en: "+ Add", ms: "+ Tambah", th: "+ เพิ่ม", fil: "+ Idagdag", vi: "+ Thêm" },
  "maintenance.parts.alertSelectPart": { id: "Pilih sparepart/komponen yang dipakai.", en: "Select the part/component used.", ms: "Pilih alat ganti/komponen yang digunakan.", th: "โปรดเลือกอะไหล่/ชิ้นส่วนที่ใช้", fil: "Pumili ng spare part/component na ginamit.", vi: "Chọn linh kiện/phụ tùng đã dùng." },

  // --- Gamepad Tester (/dashboard/maintenance/gamepad-tester) ---
  "maintenance.gamepad.promoTitle": { id: "Gamepad Tester — Cek Controller PS3/PS4/PS5", en: "Gamepad Tester — Check PS3/PS4/PS5 Controllers", ms: "Gamepad Tester — Semak Kawalan PS3/PS4/PS5", th: "Gamepad Tester — ตรวจสอบจอย PS3/PS4/PS5", fil: "Gamepad Tester — Suriin ang PS3/PS4/PS5 Controller", vi: "Gamepad Tester — Kiểm tra tay cầm PS3/PS4/PS5" },
  "maintenance.gamepad.promoDesc": { id: "Sambungkan controller ke PC, cek tiap tombol & deteksi stick drift secara langsung sebelum dipakai customer.", en: "Connect a controller to your PC, check every button & detect stick drift live before handing it to a customer.", ms: "Sambungkan kawalan ke PC, semak setiap butang & kesan drift stick secara langsung sebelum diberi kepada pelanggan.", th: "เชื่อมต่อจอยกับ PC ตรวจสอบทุกปุ่มและตรวจจับอาการ stick drift แบบสดก่อนให้ลูกค้าใช้", fil: "Ikonekta ang controller sa PC, suriin ang bawat button at tuklasin ang stick drift bago ibigay sa customer.", vi: "Kết nối tay cầm với PC, kiểm tra từng nút & phát hiện lệch cần analog trực tiếp trước khi đưa cho khách." },
  "maintenance.gamepad.promoButton": { id: "Buka Gamepad Tester", en: "Open Gamepad Tester", ms: "Buka Gamepad Tester", th: "เปิด Gamepad Tester", fil: "Buksan ang Gamepad Tester", vi: "Mở Gamepad Tester" },
  "maintenance.gamepad.backLink": { id: "← Kembali ke Maintenance", en: "← Back to Maintenance", ms: "← Kembali ke Maintenance", th: "← กลับไปที่ Maintenance", fil: "← Bumalik sa Maintenance", vi: "← Quay lại Bảo trì" },
  "maintenance.gamepad.title": { id: "Gamepad Tester — Cek Controller PS3/PS4/PS5", en: "Gamepad Tester — Check PS3/PS4/PS5 Controllers", ms: "Gamepad Tester — Semak Kawalan PS3/PS4/PS5", th: "Gamepad Tester — ตรวจสอบจอย PS3/PS4/PS5", fil: "Gamepad Tester — Suriin ang PS3/PS4/PS5 Controller", vi: "Gamepad Tester — Kiểm tra tay cầm PS3/PS4/PS5" },
  "maintenance.gamepad.subtitle": { id: "Sambungkan controller lewat USB atau Bluetooth ke PC/laptop yang membuka halaman ini, lalu tekan tombol/gerakkan stick — hasil dibaca langsung dari hardware, bukan simulasi.", en: "Connect a controller via USB or Bluetooth to the PC/laptop that has this page open, then press a button/move the stick — readings come straight from the hardware, not a simulation.", ms: "Sambungkan kawalan melalui USB atau Bluetooth ke PC/laptop yang membuka halaman ini, kemudian tekan butang/gerakkan stick — bacaan diambil terus dari perkakasan, bukan simulasi.", th: "เชื่อมต่อจอยผ่าน USB หรือ Bluetooth กับ PC/แล็ปท็อปที่เปิดหน้านี้ แล้วกดปุ่ม/ขยับ stick — ค่าที่อ่านได้มาจากฮาร์ดแวร์จริง ไม่ใช่การจำลอง", fil: "Ikonekta ang controller via USB o Bluetooth sa PC/laptop na nagbukas ng page na ito, pagkatapos ay pindutin ang button/igalaw ang stick — ang mga reading ay diretso mula sa hardware, hindi simulation.", vi: "Kết nối tay cầm qua USB hoặc Bluetooth với PC/laptop đang mở trang này, sau đó nhấn nút/di chuyển cần analog — số liệu đọc trực tiếp từ phần cứng, không phải mô phỏng." },
  "maintenance.gamepad.notSupported": { id: "Browser ini tidak mendukung Gamepad API. Coba buka halaman ini lewat Google Chrome atau Microsoft Edge terbaru.", en: "This browser doesn't support the Gamepad API. Try opening this page in a recent Google Chrome or Microsoft Edge.", ms: "Pelayar ini tidak menyokong Gamepad API. Cuba buka halaman ini melalui Google Chrome atau Microsoft Edge terkini.", th: "เบราว์เซอร์นี้ไม่รองรับ Gamepad API ลองเปิดหน้านี้ด้วย Google Chrome หรือ Microsoft Edge เวอร์ชันล่าสุด", fil: "Hindi sinusuportahan ng browser na ito ang Gamepad API. Subukang buksan ang page na ito sa bagong Google Chrome o Microsoft Edge.", vi: "Trình duyệt này không hỗ trợ Gamepad API. Hãy thử mở trang này bằng Google Chrome hoặc Microsoft Edge mới nhất." },
  "maintenance.gamepad.waiting": { id: "Belum ada controller terdeteksi — sambungkan controller lalu tekan sembarang tombol sekali (biasanya perlu 1x tekan tombol dulu agar browser mendeteksinya).", en: "No controller detected yet — connect one and press any button once (browsers usually need one button press before they detect it).", ms: "Belum ada kawalan dikesan — sambungkan kawalan kemudian tekan mana-mana butang sekali (pelayar biasanya perlu 1x tekan butang dahulu untuk mengesannya).", th: "ยังไม่พบจอย — เชื่อมต่อจอยแล้วกดปุ่มใดก็ได้หนึ่งครั้ง (โดยทั่วไปเบราว์เซอร์ต้องการการกดปุ่มหนึ่งครั้งก่อนจะตรวจพบ)", fil: "Wala pang controller na na-detect — ikonekta ang controller pagkatapos ay pindutin ang kahit anong button minsan (kadalasan kailangan ng 1x pindot ng button bago ito ma-detect ng browser).", vi: "Chưa phát hiện tay cầm nào — kết nối tay cầm rồi nhấn bất kỳ nút nào một lần (trình duyệt thường cần nhấn nút một lần trước khi phát hiện được)." },
  "maintenance.gamepad.nonStandardMapping": { id: "Mapping non-standar — cek driver controller", en: "Non-standard mapping — check controller driver", ms: "Pemetaan bukan standard — semak pemacu kawalan", th: "การแม็ปแบบไม่มาตรฐาน — ตรวจสอบไดรเวอร์จอย", fil: "Non-standard na mapping — suriin ang driver ng controller", vi: "Ánh xạ không chuẩn — kiểm tra driver tay cầm" },
  "maintenance.gamepad.driftHint": { id: "Lepas kedua stick — kalau titik biru tidak balik ke tengah lingkaran, kemungkinan stick sudah drift dan perlu diservis/diganti.", en: "Release both sticks — if the blue dot doesn't return to the center of the circle, the stick may have drift and needs servicing/replacement.", ms: "Lepaskan kedua-dua stick — jika titik biru tidak kembali ke tengah bulatan, kemungkinan stick sudah drift dan perlu diservis/digantikan.", th: "ปล่อย stick ทั้งสอง — ถ้าจุดสีฟ้าไม่กลับไปที่ศูนย์กลางวงกลม อาจแปลว่า stick เกิดอาการ drift และต้องซ่อม/เปลี่ยน", fil: "Bitawan ang dalawang stick — kung hindi bumalik ang asul na tuldok sa gitna ng bilog, posibleng may drift na ang stick at kailangang iserbisyo/palitan.", vi: "Thả cả hai cần analog — nếu chấm xanh không quay về giữa vòng tròn, cần analog có thể bị lệch và cần bảo trì/thay thế." },
  "maintenance.gamepad.helpHeading": { id: "Soal Akurasi", en: "About Accuracy", ms: "Tentang Ketepatan", th: "เกี่ยวกับความแม่นยำ", fil: "Tungkol sa Katumpakan", vi: "Về độ chính xác" },
  "maintenance.gamepad.helpBody": {
    id: "PS4 (DualShock 4) dan PS5 (DualSense) terbaca sangat akurat lewat USB maupun Bluetooth di Chrome/Edge — posisi stick, tekanan trigger, dan status tiap tombol diambil langsung dari hardware. PS3 (DualShock 3) di Windows kadang perlu driver tambahan dulu (DS3 Windows driver) agar terbaca benar — kalau muncul peringatan \"mapping non-standar\" di atas, itu tandanya. Alat ini tidak bisa membaca fitur khusus DualSense (adaptive trigger, gyro) atau mengontrol getaran — hanya untuk cek fungsi tombol dan stick.",
    en: "PS4 (DualShock 4) and PS5 (DualSense) read very accurately via USB or Bluetooth in Chrome/Edge — stick position, trigger pressure, and every button's status come straight from the hardware. PS3 (DualShock 3) on Windows sometimes needs an extra driver (DS3 Windows driver) to read correctly — the \"non-standard mapping\" warning above is the sign of that. This tool can't read DualSense-specific features (adaptive trigger, gyro) or control vibration — it's only for checking button and stick function.",
    ms: "PS4 (DualShock 4) dan PS5 (DualSense) dibaca dengan sangat tepat melalui USB atau Bluetooth di Chrome/Edge — kedudukan stick, tekanan trigger, dan status setiap butang diambil terus dari perkakasan. PS3 (DualShock 3) di Windows kadangkala memerlukan pemacu tambahan (DS3 Windows driver) untuk dibaca dengan betul — jika muncul amaran \"pemetaan bukan standard\" di atas, itu tandanya. Alat ini tidak boleh membaca ciri khusus DualSense (adaptive trigger, gyro) atau mengawal getaran — hanya untuk semak fungsi butang dan stick.",
    th: "PS4 (DualShock 4) และ PS5 (DualSense) อ่านค่าได้แม่นยำมากผ่าน USB หรือ Bluetooth ใน Chrome/Edge — ตำแหน่ง stick แรงกดทริกเกอร์ และสถานะปุ่มทุกปุ่มมาจากฮาร์ดแวร์โดยตรง PS3 (DualShock 3) บน Windows บางครั้งต้องใช้ไดรเวอร์เพิ่มเติม (DS3 Windows driver) เพื่อให้อ่านค่าได้ถูกต้อง — หากมีคำเตือน \"การแม็ปแบบไม่มาตรฐาน\" ด้านบน นั่นคือสัญญาณ เครื่องมือนี้ไม่สามารถอ่านฟีเจอร์เฉพาะของ DualSense (adaptive trigger, gyro) หรือควบคุมการสั่นได้ — ใช้ได้แค่ตรวจสอบการทำงานของปุ่มและ stick เท่านั้น",
    fil: "Ang PS4 (DualShock 4) at PS5 (DualSense) ay nababasa nang napakatumpak via USB o Bluetooth sa Chrome/Edge — ang posisyon ng stick, presyon ng trigger, at status ng bawat button ay diretso mula sa hardware. Ang PS3 (DualShock 3) sa Windows kung minsan ay nangangailangan ng karagdagang driver (DS3 Windows driver) para mabasa nang tama — kung lumabas ang babalang \"non-standard mapping\" sa itaas, iyon ang senyales. Hindi mababasa ng tool na ito ang mga natatanging feature ng DualSense (adaptive trigger, gyro) o kontrolin ang vibration — para lang ito sa pagsuri ng function ng button at stick.",
    vi: "PS4 (DualShock 4) và PS5 (DualSense) đọc rất chính xác qua USB hoặc Bluetooth trên Chrome/Edge — vị trí cần analog, lực bấm cò, và trạng thái từng nút đều lấy trực tiếp từ phần cứng. PS3 (DualShock 3) trên Windows đôi khi cần driver bổ sung (DS3 Windows driver) để đọc đúng — cảnh báo \"ánh xạ không chuẩn\" ở trên chính là dấu hiệu đó. Công cụ này không đọc được các tính năng riêng của DualSense (adaptive trigger, gyro) hay điều khiển rung — chỉ dùng để kiểm tra chức năng nút và cần analog.",
  },
});
