import { registerDict } from "./registry";

/**
 * Translations for /dashboard/shift — cashier shift open/close, physical cash
 * denomination counting, non-cash channel balance verification, and shift
 * history. Registered as a side effect on import; import this file from the
 * shift page before any component on that page calls useDashboardLang().t().
 */
registerDict({
  // --- Page header ---
  "shift.pageTitle": { id: "Shift & Kasir", en: "Shift & Cashier", ms: "Syif & Juruwang", th: "กะและแคชเชียร์", fil: "Shift at Cashier", vi: "Ca làm & Thu ngân" },
  "shift.pageSubtitle": { id: "Buka shift dengan modal awal, tutup dengan hitung fisik kas per pecahan — selisih terdeteksi otomatis, baru ditampilkan setelah hitungan disubmit.", en: "Open a shift with starting cash, close it by physically counting cash per denomination — variance is detected automatically and only shown after you submit the count.", ms: "Buka syif dengan modal permulaan, tutup dengan mengira fizikal tunai mengikut pecahan — perbezaan dikesan secara automatik dan hanya dipaparkan selepas kiraan dihantar.", th: "เปิดกะด้วยเงินทุนเริ่มต้น ปิดกะด้วยการนับเงินสดจริงตามมูลค่าธนบัตร/เหรียญ — ผลต่างจะถูกตรวจพบอัตโนมัติและแสดงหลังจากส่งการนับแล้วเท่านั้น", fil: "Magbukas ng shift gamit ang panimulang cash, isara ito sa pamamagitan ng pisikal na pagbibilang ng cash ayon sa denominasyon — awtomatikong nade-detect ang variance at ipapakita lang pagkatapos mong i-submit ang bilang.", vi: "Mở ca với tiền vốn ban đầu, đóng ca bằng cách đếm tiền mặt thực tế theo từng mệnh giá — chênh lệch được phát hiện tự động và chỉ hiển thị sau khi bạn gửi kết quả đếm." },
  "shift.staffLabel": { id: "Staf", en: "Staff", ms: "Staf", th: "พนักงาน", fil: "Staff", vi: "Nhân viên" },

  // --- Deposit balance channels management ---
  "shift.depositChannelsTitle": { id: "Channel Saldo Deposit (Non-Tunai)", en: "Deposit Balance Channels (Non-Cash)", ms: "Saluran Baki Deposit (Bukan Tunai)", th: "ช่องทางยอดเงินฝาก (ไม่ใช่เงินสด)", fil: "Deposit Balance Channels (Non-Cash)", vi: "Kênh số dư ký quỹ (phi tiền mặt)" },
  "shift.depositChannelsDesc": { id: 'Daftar ini yang muncul di "Verifikasi Saldo Channel Non-Tunai" saat tutup shift — Saldo Deposit Fastpay (PPOB) bisa diganti namanya, dan kamu bisa menambah channel saldo deposit lain (mis. provider PPOB kedua). Setiap channel otomatis terhubung ke akun COA sendiri — tambah/hapus channel di sini akan ikut membuat/menghapus akun COA-nya.', en: 'This list is what shows up under "Non-Cash Channel Balance Verification" when closing a shift — Fastpay (PPOB) Deposit Balance can be renamed, and you can add other deposit-balance channels (e.g. a second PPOB provider). Each channel is automatically linked to its own COA account — adding/deleting a channel here also creates/removes its COA account.', ms: 'Senarai ini yang dipaparkan di "Pengesahan Baki Saluran Bukan Tunai" semasa menutup syif — Baki Deposit Fastpay (PPOB) boleh ditukar nama, dan anda boleh menambah saluran baki deposit lain (cth. pembekal PPOB kedua). Setiap saluran disambungkan secara automatik ke akaun COA sendiri — menambah/memadam saluran di sini turut mencipta/memadam akaun COA-nya.', th: 'รายการนี้จะปรากฏใน "ตรวจสอบยอดคงเหลือช่องทางที่ไม่ใช่เงินสด" ตอนปิดกะ — ยอดเงินฝาก Fastpay (PPOB) สามารถเปลี่ยนชื่อได้ และคุณสามารถเพิ่มช่องทางยอดเงินฝากอื่นได้ (เช่น ผู้ให้บริการ PPOB รายที่สอง) แต่ละช่องทางจะเชื่อมโยงกับบัญชี COA ของตัวเองโดยอัตโนมัติ — การเพิ่ม/ลบช่องทางที่นี่จะสร้าง/ลบบัญชี COA ไปพร้อมกันด้วย', fil: 'Ang listahang ito ang lumalabas sa "Beripikasyon ng Balanse ng Non-Cash Channel" kapag nagsasara ng shift — ang Deposit Balance ng Fastpay (PPOB) ay maaaring palitan ng pangalan, at maaari kang magdagdag ng ibang deposit-balance channel (hal. pangalawang PPOB provider). Bawat channel ay awtomatikong konektado sa sarili nitong account sa COA — ang pagdagdag/pagtanggal ng channel dito ay gagawa/magtatanggal din ng COA account nito.', vi: 'Danh sách này sẽ hiển thị trong mục "Xác minh số dư kênh phi tiền mặt" khi đóng ca — Số dư ký quỹ Fastpay (PPOB) có thể đổi tên, và bạn có thể thêm các kênh số dư ký quỹ khác (ví dụ nhà cung cấp PPOB thứ hai). Mỗi kênh sẽ tự động liên kết với một tài khoản COA riêng — thêm/xóa kênh ở đây cũng sẽ tạo/xóa tài khoản COA tương ứng.' },
  "shift.save": { id: "Simpan", en: "Save", ms: "Simpan", th: "บันทึก", fil: "I-save", vi: "Lưu" },
  "shift.cancel": { id: "Batal", en: "Cancel", ms: "Batal", th: "ยกเลิก", fil: "Kanselahin", vi: "Hủy" },
  "shift.systemBadge": { id: "Sistem", en: "System", ms: "Sistem", th: "ระบบ", fil: "System", vi: "Hệ thống" },
  "shift.rename": { id: "Ganti Nama", en: "Rename", ms: "Tukar Nama", th: "เปลี่ยนชื่อ", fil: "Palitan ang Pangalan", vi: "Đổi tên" },
  "shift.delete": { id: "Hapus", en: "Delete", ms: "Padam", th: "ลบ", fil: "Tanggalin", vi: "Xóa" },
  "shift.deleting": { id: "Menghapus...", en: "Deleting...", ms: "Memadam...", th: "กำลังลบ...", fil: "Tinatanggal...", vi: "Đang xóa..." },
  "shift.deleteTooltipReady": { id: "Hapus riwayat shift ini", en: "Delete this shift record", ms: "Padam rekod syif ini", th: "ลบประวัติกะนี้", fil: "Tanggalin ang record ng shift na ito", vi: "Xóa lịch sử ca này" },
  "shift.deleteTooltipNotClosed": { id: "Tutup shift ini dulu sebelum bisa dihapus", en: "Close this shift before it can be deleted", ms: "Tutup syif ini dahulu sebelum boleh dipadam", th: "ต้องปิดกะนี้ก่อนจึงจะลบได้", fil: "Isara muna ang shift na ito bago ito matanggal", vi: "Phải đóng ca này trước khi có thể xóa" },
  "shift.newChannelPlaceholder": { id: "Nama channel saldo deposit baru, mis. Saldo Deposit Midtrans", en: "New deposit-balance channel name, e.g. Midtrans Deposit Balance", ms: "Nama saluran baki deposit baharu, cth. Baki Deposit Midtrans", th: "ชื่อช่องทางยอดเงินฝากใหม่ เช่น ยอดเงินฝาก Midtrans", fil: "Pangalan ng bagong deposit-balance channel, hal. Midtrans Deposit Balance", vi: "Tên kênh số dư ký quỹ mới, ví dụ Số dư ký quỹ Midtrans" },
  "shift.addChannel": { id: "Tambah Channel", en: "Add Channel", ms: "Tambah Saluran", th: "เพิ่มช่องทาง", fil: "Magdagdag ng Channel", vi: "Thêm kênh" },

  // --- Active shift / cash count ---
  "shift.activeShiftTitle": { id: "Shift Aktif", en: "Active Shift", ms: "Syif Aktif", th: "กะที่กำลังดำเนินการ", fil: "Aktibong Shift", vi: "Ca đang hoạt động" },
  "shift.runningSince": { id: "Berjalan sejak {time}", en: "Running since {time}", ms: "Berjalan sejak {time}", th: "ดำเนินการตั้งแต่ {time}", fil: "Tumatakbo simula {time}", vi: "Đang chạy từ {time}" },
  "shift.openingCashLabel": { id: "Modal awal:", en: "Starting cash:", ms: "Modal permulaan:", th: "เงินทุนเริ่มต้น:", fil: "Panimulang cash:", vi: "Tiền vốn ban đầu:" },
  "shift.cashCountTitle": { id: "Hitung Fisik Kas (Per Pecahan)", en: "Physical Cash Count (By Denomination)", ms: "Kiraan Fizikal Tunai (Mengikut Pecahan)", th: "การนับเงินสดจริง (แยกตามมูลค่า)", fil: "Pisikal na Bilang ng Cash (Ayon sa Denominasyon)", vi: "Kiểm đếm tiền mặt thực tế (theo mệnh giá)" },
  "shift.cashCountDesc": { id: "Hitung uang di laci satu per satu sesuai pecahan — jangan lihat laporan sistem dulu. Total akan muncul otomatis saat kamu mengisi.", en: "Count the cash in the drawer one denomination at a time — don't check the system report first. The total appears automatically as you fill it in.", ms: "Kira wang dalam laci satu demi satu mengikut pecahan — jangan lihat laporan sistem dahulu. Jumlah akan dipaparkan secara automatik semasa anda mengisi.", th: "นับเงินในลิ้นชักทีละมูลค่า — อย่าเพิ่งดูรายงานจากระบบ ยอดรวมจะปรากฏอัตโนมัติขณะที่คุณกรอกข้อมูล", fil: "Bilangin ang pera sa drawer isa-isa ayon sa denominasyon — huwag munang tingnan ang report ng system. Awtomatikong lalabas ang total habang pinupunan mo ito.", vi: "Đếm tiền trong ngăn kéo từng mệnh giá một — đừng xem báo cáo hệ thống trước. Tổng số sẽ tự động hiện ra khi bạn nhập." },
  "shift.totalCountedLabel": { id: "Total Hitungan Fisik", en: "Physical Count Total", ms: "Jumlah Kiraan Fizikal", th: "ยอดรวมจากการนับจริง", fil: "Kabuuang Pisikal na Bilang", vi: "Tổng số đếm thực tế" },

  // --- Non-cash channel balance verification ---
  "shift.verifyBalanceTitle": { id: "Verifikasi Saldo Channel Non-Tunai", en: "Non-Cash Channel Balance Verification", ms: "Pengesahan Baki Saluran Bukan Tunai", th: "ตรวจสอบยอดคงเหลือช่องทางที่ไม่ใช่เงินสด", fil: "Beripikasyon ng Balanse ng Non-Cash Channel", vi: "Xác minh số dư kênh phi tiền mặt" },
  "shift.verifyBalanceDesc": { id: "Buka app/dashboard masing-masing channel dan masukkan saldo yang tertera di sana saat ini.", en: "Open each channel's app/dashboard and enter the balance currently shown there.", ms: "Buka aplikasi/papan pemuka setiap saluran dan masukkan baki yang dipaparkan di sana pada masa ini.", th: "เปิดแอป/แดชบอร์ดของแต่ละช่องทางแล้วกรอกยอดคงเหลือที่แสดงอยู่ในขณะนั้น", fil: "Buksan ang app/dashboard ng bawat channel at ilagay ang balanse na kasalukuyang ipinapakita doon.", vi: "Mở ứng dụng/bảng điều khiển của từng kênh và nhập số dư hiện đang hiển thị ở đó." },
  "shift.balancePlaceholder": { id: "Saldo di app", en: "Balance in app", ms: "Baki dalam aplikasi", th: "ยอดคงเหลือในแอป", fil: "Balanse sa app", vi: "Số dư trong ứng dụng" },

  // --- Notes + close/open shift actions ---
  "shift.notesLabel": { id: "Catatan (opsional)", en: "Notes (optional)", ms: "Nota (pilihan)", th: "หมายเหตุ (ไม่บังคับ)", fil: "Mga Tala (opsyonal)", vi: "Ghi chú (không bắt buộc)" },
  "shift.notesPlaceholder": { id: "Mis. alasan jika ada selisih yang sudah diketahui sebelumnya", en: "E.g. the reason if there's already a known variance", ms: "Cth. sebab jika terdapat perbezaan yang telah diketahui sebelum ini", th: "เช่น เหตุผลหากมีผลต่างที่ทราบอยู่แล้วก่อนหน้านี้", fil: "Hal. dahilan kung mayroon nang alam na variance", vi: "Ví dụ: lý do nếu đã biết trước có chênh lệch" },
  "shift.closing": { id: "Menutup...", en: "Closing...", ms: "Menutup...", th: "กำลังปิด...", fil: "Isinasara...", vi: "Đang đóng..." },
  "shift.closeShiftBtn": { id: "Tutup Shift", en: "Close Shift", ms: "Tutup Syif", th: "ปิดกะ", fil: "Isara ang Shift", vi: "Đóng ca" },
  "shift.openNewShiftTitle": { id: "Buka Shift Baru", en: "Open New Shift", ms: "Buka Syif Baharu", th: "เปิดกะใหม่", fil: "Magbukas ng Bagong Shift", vi: "Mở ca mới" },
  "shift.openingCashPlaceholder": { id: "Modal awal kas", en: "Starting cash amount", ms: "Jumlah modal permulaan tunai", th: "จำนวนเงินทุนเริ่มต้น", fil: "Halaga ng panimulang cash", vi: "Số tiền vốn ban đầu" },
  "shift.openShiftBtn": { id: "Buka Shift", en: "Open Shift", ms: "Buka Syif", th: "เปิดกะ", fil: "Buksan ang Shift", vi: "Mở ca" },

  // --- Close summary reveal ---
  "shift.closeSummaryTitle": { id: "Ringkasan Tutup Shift", en: "Shift Close Summary", ms: "Ringkasan Penutupan Syif", th: "สรุปการปิดกะ", fil: "Buod ng Pagsasara ng Shift", vi: "Tóm tắt đóng ca" },
  "shift.downloadReportBtn": { id: "Download Berita Acara (PDF)", en: "Download Handover Report (PDF)", ms: "Muat Turun Laporan Serah Terima (PDF)", th: "ดาวน์โหลดรายงานส่งมอบ (PDF)", fil: "I-download ang Ulat ng Paghahanda (PDF)", vi: "Tải biên bản bàn giao (PDF)" },
  "shift.cashInLabel": { id: "Kas Masuk", en: "Cash In", ms: "Tunai Masuk", th: "เงินสดเข้า", fil: "Cash In", vi: "Tiền vào" },
  "shift.cashOutLabel": { id: "Kas Keluar", en: "Cash Out", ms: "Tunai Keluar", th: "เงินสดออก", fil: "Cash Out", vi: "Tiền ra" },
  "shift.expectedCashLabel": { id: "Ekspektasi Kas", en: "Expected Cash", ms: "Jangkaan Tunai", th: "เงินสดที่คาดไว้", fil: "Inaasahang Cash", vi: "Tiền mặt dự kiến" },
  "shift.cashVarianceLabel": { id: "Selisih Kas", en: "Cash Variance", ms: "Perbezaan Tunai", th: "ผลต่างเงินสด", fil: "Variance ng Cash", vi: "Chênh lệch tiền mặt" },
  "shift.shortSuffixLower": { id: " (kurang)", en: " (short)", ms: " (kurang)", th: " (ขาด)", fil: " (kulang)", vi: " (thiếu)" },
  "shift.overSuffixLower": { id: " (lebih)", en: " (over)", ms: " (lebih)", th: " (เกิน)", fil: " (sobra)", vi: " (dư)" },
  "shift.varianceShort": { id: "(Kurang)", en: "(Short)", ms: "(Kurang)", th: "(ขาด)", fil: "(Kulang)", vi: "(Thiếu)" },
  "shift.varianceOver": { id: "(Lebih)", en: "(Over)", ms: "(Lebih)", th: "(เกิน)", fil: "(Sobra)", vi: "(Dư)" },
  "shift.colChannel": { id: "Channel", en: "Channel", ms: "Saluran", th: "ช่องทาง", fil: "Channel", vi: "Kênh" },
  "shift.colExpected": { id: "Ekspektasi", en: "Expected", ms: "Jangkaan", th: "คาดไว้", fil: "Inaasahan", vi: "Dự kiến" },
  "shift.colActual": { id: "Aktual", en: "Actual", ms: "Sebenar", th: "จริง", fil: "Aktwal", vi: "Thực tế" },
  "shift.colVariance": { id: "Selisih", en: "Variance", ms: "Perbezaan", th: "ผลต่าง", fil: "Variance", vi: "Chênh lệch" },

  // --- Shift history ---
  "shift.historyTitle": { id: "Riwayat Shift", en: "Shift History", ms: "Sejarah Syif", th: "ประวัติกะ", fil: "Kasaysayan ng Shift", vi: "Lịch sử ca" },
  "shift.historyDescPrefix": { id: "Setiap pergantian shift otomatis dicek selisih kas (fisik vs ekspektasi sistem) dan selisih saldo channel non-tunai — ditandai", en: "Every shift change automatically checks the cash variance (physical vs. system expectation) and the non-cash channel balance variance — flagged", ms: "Setiap pertukaran syif secara automatik menyemak perbezaan tunai (fizikal berbanding jangkaan sistem) dan perbezaan baki saluran bukan tunai — ditanda", th: "ทุกครั้งที่เปลี่ยนกะ ระบบจะตรวจสอบผลต่างเงินสด (เงินจริงเทียบกับที่ระบบคาดไว้) และผลต่างยอดคงเหลือช่องทางที่ไม่ใช่เงินสดโดยอัตโนมัติ — ทำเครื่องหมายเป็น", fil: "Bawat pagpapalit ng shift ay awtomatikong sinusuri ang variance ng cash (pisikal kumpara sa inaasahan ng system) at variance ng balanse ng non-cash channel — minarkahan", vi: "Mỗi lần đổi ca, hệ thống tự động kiểm tra chênh lệch tiền mặt (thực tế so với dự kiến của hệ thống) và chênh lệch số dư kênh phi tiền mặt — được đánh dấu" },
  "shift.historyDescRedLabel": { id: 'merah "Kurang"', en: 'red "Short"', ms: 'merah "Kurang"', th: 'สีแดง "ขาด"', fil: 'pulang "Kulang"', vi: 'màu đỏ "Thiếu"' },
  "shift.historyDescMiddle": { id: "untuk kekurangan dan", en: "for a shortage and", ms: "untuk kekurangan dan", th: "สำหรับกรณีขาด และ", fil: "para sa kakulangan at", vi: "cho trường hợp thiếu và" },
  "shift.historyDescAmberLabel": { id: 'kuning "Lebih"', en: 'amber "Over"', ms: 'kuning "Lebih"', th: 'สีเหลือง "เกิน"', fil: 'dilaw "Sobra"', vi: 'màu hổ phách "Dư"' },
  "shift.historyDescSuffix": { id: "untuk kelebihan, supaya keduanya sama-sama kelihatan, bukan cuma yang kurang.", en: "for an overage, so both are equally visible, not just shortages.", ms: "untuk kelebihan, supaya kedua-duanya sama-sama kelihatan, bukan hanya kekurangan.", th: "สำหรับกรณีเกิน เพื่อให้มองเห็นทั้งสองกรณีเท่าๆ กัน ไม่ใช่แค่กรณีที่ขาด", fil: "para sa sobra, para pareho itong makikita, hindi lang ang kakulangan.", vi: "cho trường hợp dư, để cả hai trường hợp đều dễ nhìn thấy, không chỉ riêng phần thiếu." },
  "shift.colOpen": { id: "Buka", en: "Opened", ms: "Dibuka", th: "เปิด", fil: "Binuksan", vi: "Mở" },
  "shift.colClose": { id: "Tutup", en: "Closed", ms: "Ditutup", th: "ปิด", fil: "Isinara", vi: "Đóng" },
  "shift.colStaff": { id: "Karyawan", en: "Employee", ms: "Kakitangan", th: "พนักงาน", fil: "Empleyado", vi: "Nhân viên" },
  "shift.colOpeningCapital": { id: "Modal", en: "Starting Cash", ms: "Modal", th: "เงินทุน", fil: "Panimulang Cash", vi: "Vốn" },
  "shift.colNonCashVariance": { id: "Selisih Non-Tunai", en: "Non-Cash Variance", ms: "Perbezaan Bukan Tunai", th: "ผลต่างที่ไม่ใช่เงินสด", fil: "Variance ng Non-Cash", vi: "Chênh lệch phi tiền mặt" },
  "shift.pdfLink": { id: "PDF", en: "PDF", ms: "PDF", th: "PDF", fil: "PDF", vi: "PDF" },

  // --- Alerts / confirms ---
  "shift.confirmDeleteChannel": { id: 'Hapus channel "{label}"? Akun COA yang terkait akan otomatis dihapus/diarsipkan bersamaan.', en: 'Delete channel "{label}"? Its linked COA account will be automatically deleted/archived along with it.', ms: 'Padam saluran "{label}"? Akaun COA yang berkaitan akan dipadam/diarkibkan secara automatik bersama-sama.', th: 'ลบช่องทาง "{label}" หรือไม่? บัญชี COA ที่เกี่ยวข้องจะถูกลบ/เก็บถาวรโดยอัตโนมัติไปพร้อมกัน', fil: 'Tanggalin ang channel na "{label}"? Awtomatikong matatanggal/ma-archive ang kaugnay na COA account kasabay nito.', vi: 'Xóa kênh "{label}"? Tài khoản COA liên kết sẽ tự động bị xóa/lưu trữ cùng lúc.' },
  "shift.confirmDeleteShift": { id: "Hapus riwayat shift ini (dibuka {openedAt}, kasir {staffName})? Tidak bisa dibatalkan.", en: "Delete this shift record (opened {openedAt}, cashier {staffName})? This cannot be undone.", ms: "Padam rekod syif ini (dibuka {openedAt}, juruwang {staffName})? Ini tidak boleh dibatalkan.", th: "ลบประวัติกะนี้ (เปิดเมื่อ {openedAt} แคชเชียร์ {staffName}) หรือไม่? ไม่สามารถยกเลิกได้", fil: "Tanggalin ang record ng shift na ito (binuksan {openedAt}, cashier {staffName})? Hindi na ito maibabalik.", vi: "Xóa lịch sử ca này (mở lúc {openedAt}, thu ngân {staffName})? Không thể hoàn tác." },
  "shift.missingBalanceAlert": { id: "Saldo aktual belum diisi untuk: {list}", en: "Actual balance not yet filled in for: {list}", ms: "Baki sebenar belum diisi untuk: {list}", th: "ยังไม่ได้กรอกยอดคงเหลือจริงสำหรับ: {list}", fil: "Hindi pa napunan ang aktwal na balanse para sa: {list}", vi: "Chưa nhập số dư thực tế cho: {list}" },
  "shift.confirmCloseShift": { id: "Pastikan hitungan fisik sudah final sebelum submit — setelah ini tidak bisa diubah. Lanjutkan tutup shift?", en: "Make sure the physical count is final before submitting — it can't be changed after this. Continue closing the shift?", ms: "Pastikan kiraan fizikal sudah muktamad sebelum menghantar — selepas ini tidak boleh diubah. Teruskan menutup syif?", th: "ตรวจสอบให้แน่ใจว่าการนับจริงเป็นค่าสุดท้ายก่อนส่ง — หลังจากนี้จะไม่สามารถแก้ไขได้ ต้องการปิดกะต่อหรือไม่?", fil: "Siguraduhing final na ang pisikal na bilang bago mag-submit — hindi na ito mababago pagkatapos nito. Ituloy ang pagsasara ng shift?", vi: "Đảm bảo số đếm thực tế là số liệu cuối cùng trước khi gửi — sau bước này sẽ không thể thay đổi. Tiếp tục đóng ca?" },
});
