import { registerDict } from "./registry";

/** Teks netral "mode aplikasi Android" (tanpa tombol/tautan pembayaran) — lihat lib/app-mode.ts. */
registerDict({
  "appMode.managedNote": { id: "Langganan dikelola melalui akun NEXBILL Anda.", en: "Your subscription is managed through your NEXBILL account.", ms: "Langganan diuruskan melalui akaun NEXBILL anda.", th: "การสมัครสมาชิกจัดการผ่านบัญชี NEXBILL ของคุณ", fil: "Ang subscription ay pinamamahalaan sa iyong NEXBILL account.", vi: "Gói đăng ký được quản lý qua tài khoản NEXBILL của bạn." },
  "appMode.lockedNote": { id: "Akses outlet ini sedang tidak aktif. Langganan dikelola melalui akun NEXBILL Anda — data outlet tetap aman.", en: "Access for this outlet is currently inactive. Your subscription is managed through your NEXBILL account — outlet data stays safe.", ms: "Akses outlet ini tidak aktif buat masa ini. Langganan diuruskan melalui akaun NEXBILL anda — data outlet kekal selamat.", th: "การเข้าถึงสาขานี้ไม่ได้ใช้งานอยู่ การสมัครสมาชิกจัดการผ่านบัญชี NEXBILL ของคุณ — ข้อมูลสาขายังปลอดภัย", fil: "Hindi aktibo ang access ng outlet na ito. Ang subscription ay pinamamahalaan sa iyong NEXBILL account — ligtas ang data ng outlet.", vi: "Quyền truy cập cơ sở này đang không hoạt động. Gói đăng ký được quản lý qua tài khoản NEXBILL của bạn — dữ liệu cơ sở vẫn an toàn." },
  "appMode.proFeatureNote": { id: "{feature} termasuk paket NEXBILL Pro. Paket dikelola melalui akun NEXBILL Anda.", en: "{feature} is part of NEXBILL Pro. Plans are managed through your NEXBILL account.", ms: "{feature} termasuk dalam NEXBILL Pro. Pelan diuruskan melalui akaun NEXBILL anda.", th: "{feature} อยู่ในแพ็กเกจ NEXBILL Pro แพ็กเกจจัดการผ่านบัญชี NEXBILL ของคุณ", fil: "Kasama ang {feature} sa NEXBILL Pro. Ang plano ay pinamamahalaan sa iyong NEXBILL account.", vi: "{feature} thuộc gói NEXBILL Pro. Gói được quản lý qua tài khoản NEXBILL của bạn." },
  "appMode.aiNote": { id: "AI Business Intelligence termasuk paket Pro atau AI Add-on. Paket dikelola melalui akun NEXBILL Anda.", en: "AI Business Intelligence is included in Pro or the AI Add-on. Plans are managed through your NEXBILL account.", ms: "AI Business Intelligence termasuk dalam Pro atau Tambahan AI. Pelan diuruskan melalui akaun NEXBILL anda.", th: "AI Business Intelligence รวมอยู่ใน Pro หรือส่วนเสริม AI แพ็กเกจจัดการผ่านบัญชี NEXBILL ของคุณ", fil: "Kasama ang AI Business Intelligence sa Pro o sa AI Add-on. Ang plano ay pinamamahalaan sa iyong NEXBILL account.", vi: "AI Business Intelligence có trong gói Pro hoặc Tiện ích AI. Gói được quản lý qua tài khoản NEXBILL của bạn." },
  "appMode.graceNote": { id: "Masa tenggang sedang berjalan. Langganan dikelola melalui akun NEXBILL Anda.", en: "A grace period is running. Your subscription is managed through your NEXBILL account.", ms: "Tempoh tangguh sedang berjalan. Langganan diuruskan melalui akaun NEXBILL anda.", th: "อยู่ในช่วงผ่อนผัน การสมัครสมาชิกจัดการผ่านบัญชี NEXBILL ของคุณ", fil: "May grace period na tumatakbo. Ang subscription ay pinamamahalaan sa iyong NEXBILL account.", vi: "Đang trong thời gian ân hạn. Gói đăng ký được quản lý qua tài khoản NEXBILL của bạn." },
  "appMode.ok": { id: "Mengerti", en: "Got it", ms: "Faham", th: "เข้าใจแล้ว", fil: "Sige", vi: "Đã hiểu" },
});
